export const abilityTypeDefs = `
    type AbilityItem implements Item {
        ability_type: String
        behaviours: [String]
        boss_damage_scale: Float
        class_name: String!
        dependant_abilities: [String]
        description: ItemDescription
        hero: Hero
        heroes: [Hero]
        id: ID!
        image_webp: String
        image: String
        name: String
        properties: AbilityItemProperties
        start_trained: Boolean
        tooltip_details: ToolTipDetails
        type: String
        update_time: Int
        upgrades: [AbilityItemUpgrade]
        videos: Videos
        weapon_info: AbilityItemWeaponInfo
    }

    type AbilityItemWeaponInfo implements ItemWeaponInfo {
        bullet_speed_curve: BulletSpeedCurve
    }

    type Videos {
        webm: String
        mp4: String
    }

    type ToolTipDetails {
        info_sections: [InfoSection]
    }

    type InfoSection {
        loc_string: String
        property_upgrade_required: String
        properties_block: [InfoSectionPropertiesBlock]
        basic_properties: [String]
    }

    type InfoSectionPropertiesBlock {
        properties: [PropertiesBlockProperties]
    }

    type PropertiesBlockProperties {
        important_property_icon: String
        important_property: String
        requires_ability_upgrade: Boolean
        show_property_value: Boolean
        status_effect_name: String
        status_effect_value: String
    }

    type AbilityItemUpgrade {
        name: String
        bonus: String
    }

    type AbilityItemProperties implements ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityChannelTimeDisplay: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityChargesConditionally: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityCooldownPerHeadshot: ItemPropertyInfo
        AbilityCooldownPerHeadshotNPC: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityLifestealPercent: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilitySpeedPct: ItemPropertyInfo
        AbilitySplitShot: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        AccelerationPercentage: ItemPropertyInfo
        AccelSpeed: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActivationDistance: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AdditionalShockTarget: ItemPropertyInfo
        AfterburnSpiritDamageReduction: ItemPropertyInfo
        AimFOV: ItemPropertyInfo
        AimZoomDuration: ItemPropertyInfo
        AirControlAccelPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirDampingDuration: ItemPropertyInfo
        AirDrag: ItemPropertyInfo
        AirDropBulletShield: ItemPropertyInfo
        AirJumpForce: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        AirSideMoveSpeedPercentage: ItemPropertyInfo
        AirSpeedBonus: ItemPropertyInfo
        AirSpeedMax: ItemPropertyInfo
        AlliedFireRatePercentage: ItemPropertyInfo
        AllowMovement: ItemPropertyInfo
        AllyCastDelay: ItemPropertyInfo
        AllyDistance: ItemPropertyInfo
        AllyHeight: ItemPropertyInfo
        AllyOutgoingDamagePercent: ItemPropertyInfo
        AllyRadius: ItemPropertyInfo
        AltJumpSpeed: ItemPropertyInfo
        AmpDuration: ItemPropertyInfo
        AmpPercentPerStack: ItemPropertyInfo
        AOERadius: ItemPropertyInfo
        ArmingDuration: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        ArmTime: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        AttackRadius: ItemPropertyInfo
        AttackSpeedMult: ItemPropertyInfo
        AuraEffectDuration: ItemPropertyInfo
        AuraFireRateBonus: ItemPropertyInfo
        AuraLingerDuration: ItemPropertyInfo
        BackstabBonusDamagePct: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BackwardsVelocity: ItemPropertyInfo
        BallHitRadius: ItemPropertyInfo
        BallOffset: ItemPropertyInfo
        BallRadius: ItemPropertyInfo
        BarbedWireDamagePerMeter: ItemPropertyInfo
        BarbedWireDPS: ItemPropertyInfo
        BarbedWireHeightOffGround: ItemPropertyInfo
        BarbedWireRadius: ItemPropertyInfo
        BarbedWireSlow: ItemPropertyInfo
        BarbedWireTickRate: ItemPropertyInfo
        BarrelBounceVelocity: ItemPropertyInfo
        BarrelDamage: ItemPropertyInfo
        BarrelHeavyMeleeForceForward: ItemPropertyInfo
        BarrelHeavyMeleeForceUp: ItemPropertyInfo
        BarrelLifetime: ItemPropertyInfo
        BarrelLightMeleeForceForward: ItemPropertyInfo
        BarrelLightMeleeForceUp: ItemPropertyInfo
        BarrelPitchMax: ItemPropertyInfo
        BarrelPitchMin: ItemPropertyInfo
        BarrelRollSpeedMoveAir: ItemPropertyInfo
        BarrelRollSpeedMoveMin: ItemPropertyInfo
        BarrelScale: ItemPropertyInfo
        BarrelUpFactor: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BaseBulletDamage: ItemPropertyInfo
        BaseDamage: ItemPropertyInfo
        BaseHeatPower: ItemPropertyInfo
        BatCount: ItemPropertyInfo
        BatCountPerWave: ItemPropertyInfo
        BatSpawnRadius: ItemPropertyInfo
        BatSpawnRandomAngle: ItemPropertyInfo
        BatSpawnRandomVelocity: ItemPropertyInfo
        BeamCloseDamagePercent: ItemPropertyInfo
        BeamCloseRadius: ItemPropertyInfo
        BeamEndRadius: ItemPropertyInfo
        BeamLength: ItemPropertyInfo
        BeamLifesteal: ItemPropertyInfo
        BeamLifestealNonHeroPercent: ItemPropertyInfo
        BeamSplit: ItemPropertyInfo
        BeamSplitCount: ItemPropertyInfo
        BeamWidth: ItemPropertyInfo
        BeepSoundBuildupCount: ItemPropertyInfo
        BeepSoundIntervalBias: ItemPropertyInfo
        BeepSoundMaxFrequency: ItemPropertyInfo
        BlastJumpVelocity: ItemPropertyInfo
        BlastJumpVelocityCrouch: ItemPropertyInfo
        BlastJumpVelocityGround: ItemPropertyInfo
        BlastRadius: ItemPropertyInfo
        BleedDPSPerStack: ItemPropertyInfo
        BleedDuration: ItemPropertyInfo
        BleedTickRate: ItemPropertyInfo
        BlindScale: ItemPropertyInfo
        BlockerScaleFactor: ItemPropertyInfo
        BloodSpillDPSPercent: ItemPropertyInfo
        BloodSpillDuration: ItemPropertyInfo
        BoloBounceCount: ItemPropertyInfo
        BoloBounceSpeed: ItemPropertyInfo
        BoloContractRadius: ItemPropertyInfo
        BoloHitDamage: ItemPropertyInfo
        BoloProcDamage: ItemPropertyInfo
        BoloRadius: ItemPropertyInfo
        BoltRefundPerKill: ItemPropertyInfo
        BombFriction: ItemPropertyInfo
        BombRestitution: ItemPropertyInfo
        BonusAbilityResource: ItemPropertyInfo
        BonusBatsMax: ItemPropertyInfo
        BonusBatsPerProc: ItemPropertyInfo
        BonusBulletSpeed: ItemPropertyInfo
        BonusClip: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusCritDamagePercent: ItemPropertyInfo
        BonusDamage: ItemPropertyInfo
        BonusDamageCap: ItemPropertyInfo
        BonusDamageConversionPercent: ItemPropertyInfo
        BonusDamageDecayLockoutDuration: ItemPropertyInfo
        BonusDamageDecayPerSecond: ItemPropertyInfo
        BonusDamageDecayRate: ItemPropertyInfo
        BonusDamagePctPerPlayerHit: ItemPropertyInfo
        BonusDamagePctPerPlayerKilled: ItemPropertyInfo
        BonusDamagePerBullet: ItemPropertyInfo
        BonusDamagePercent: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusFireRatePerHero: ItemPropertyInfo
        BonusGoldOnKill: ItemPropertyInfo
        BonusHealthOnKill: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusKnockbackDistance: ItemPropertyInfo
        BonusMaxHealth: ItemPropertyInfo
        BonusMaxHealthPerHero: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusMoveSpeedPercent: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusPerHeadshot: ItemPropertyInfo
        BonusSpiritLingerDuration: ItemPropertyInfo
        BonusSpiritMax: ItemPropertyInfo
        BonusSpiritMeter: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BonusStamina: ItemPropertyInfo
        BonusTechDamagePercent: ItemPropertyInfo
        BonusTechPowerPerKill: ItemPropertyInfo
        BoostTime: ItemPropertyInfo
        BossDamagePercentIncoming: ItemPropertyInfo
        BossDamagePercentOutgoing: ItemPropertyInfo
        BouncePadExtendDuration: ItemPropertyInfo
        BounceRadians: ItemPropertyInfo
        BounceRange: ItemPropertyInfo
        BounceVelocity: ItemPropertyInfo
        BreakablePropDamageRadius: ItemPropertyInfo
        BreakoutTime: ItemPropertyInfo
        BuffBaseWeaponPct: ItemPropertyInfo
        BuffDamage: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuffGunRangePercent: ItemPropertyInfo
        BuffOnKillDuration: ItemPropertyInfo
        BuffTarget: ItemPropertyInfo
        BuildUpBulletPercentPerHit: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpMaxDamage: ItemPropertyInfo
        BuildUpMaxDamageNonHero: ItemPropertyInfo
        BuildUpPerBat: ItemPropertyInfo
        BuildUpPerDagger: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BuildupProcDamage: ItemPropertyInfo
        BuildupProcDuration: ItemPropertyInfo
        BuildupSpiritDamageThreshold: ItemPropertyInfo
        BulletAccuracy: ItemPropertyInfo
        BulletAmp: ItemPropertyInfo
        BulletAmpDuration: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletArmorReductionDuration: ItemPropertyInfo
        BulletArmorReductionHeavy: ItemPropertyInfo
        BulletArmorReductionLight: ItemPropertyInfo
        BulletDamageIncrease: ItemPropertyInfo
        BulletForce: ItemPropertyInfo
        BulletLifesteal: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletRadiusOverride: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistOnActive: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletResistReductionDuration: ItemPropertyInfo
        BulletScaleFactor: ItemPropertyInfo
        BulletShieldDamageConversionPercent: ItemPropertyInfo
        BulletShieldDuration: ItemPropertyInfo
        BulletShieldHealth: ItemPropertyInfo
        BulletShieldMaxHealthPercentage: ItemPropertyInfo
        BulletShieldMissingHealthPercentage: ItemPropertyInfo
        BulletShieldPerHero: ItemPropertyInfo
        BulletShieldPoints: ItemPropertyInfo
        BulletSpeedPercent: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        BulletTimeScale: ItemPropertyInfo
        BulletVulnerbility: ItemPropertyInfo
        BurnDuration: ItemPropertyInfo
        BurstBonusPerStack: ItemPropertyInfo
        CameraDistance: ItemPropertyInfo
        CameraHeightOffset: ItemPropertyInfo
        CameraHorizontalOffset: ItemPropertyInfo
        CameraPreviewDistance: ItemPropertyInfo
        CameraPreviewOffset: ItemPropertyInfo
        CameraPreviewSpeed: ItemPropertyInfo
        CameraTurnRateMax: ItemPropertyInfo
        CanBePurged: ItemPropertyInfo
        CancelHookDuration: ItemPropertyInfo
        CanGrappleAllyHeroes: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        CardResourceGenPctScale: ItemPropertyInfo
        CardResourcePerBulletCrit: ItemPropertyInfo
        CardResourcePerBulletHit: ItemPropertyInfo
        CardResourcePerHeavyMelee: ItemPropertyInfo
        CardResourcePerLightMelee: ItemPropertyInfo
        CastRangeWhenVertical: ItemPropertyInfo
        CastRangeWhenVerticalBias: ItemPropertyInfo
        CastWhileRolling: ItemPropertyInfo
        CatAboveGround: ItemPropertyInfo
        CatAccel: ItemPropertyInfo
        CatActivateDuration: ItemPropertyInfo
        CatchRadius: ItemPropertyInfo
        CatClimbHeight: ItemPropertyInfo
        CatDropDownRate: ItemPropertyInfo
        CatFormDamageDealtReduction: ItemPropertyInfo
        CatLifetime: ItemPropertyInfo
        CatMaxSpeed: ItemPropertyInfo
        CatStartSpeed: ItemPropertyInfo
        CenterDamage: ItemPropertyInfo
        CenterRadius: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainDuration: ItemPropertyInfo
        ChainLength: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        ChannelSlowPercent: ItemPropertyInfo
        ChannelTimeForMaxDebuff: ItemPropertyInfo
        ChargeDistance: ItemPropertyInfo
        ChargeDragVerticalOffset: ItemPropertyInfo
        ChargedShotHitRadiusScale: ItemPropertyInfo
        ChargeForKill: ItemPropertyInfo
        ChargeRadius: ItemPropertyInfo
        ChargeSpeedMax: ItemPropertyInfo
        ChargeUpTime: ItemPropertyInfo
        ClimbHeight: ItemPropertyInfo
        ClimbPerGrenade: ItemPropertyInfo
        ClipSizeBonus: ItemPropertyInfo
        ClipSizeOverride: ItemPropertyInfo
        CloneBoltDelay: ItemPropertyInfo
        CloneDamagePercentage: ItemPropertyInfo
        CloneDamageTakenIncreasePercent: ItemPropertyInfo
        CloneGoldToGive: ItemPropertyInfo
        CloneHealthPercentage: ItemPropertyInfo
        CloneLifetime: ItemPropertyInfo
        CloneSpawnDistance: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CloseRangeSpeed: ItemPropertyInfo
        CloudHeight: ItemPropertyInfo
        CollidePlayersStopTime: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        ConeAngle: ItemPropertyInfo
        ConeRadius: ItemPropertyInfo
        ConsumeHealPercentage: ItemPropertyInfo
        CooldownPerStack: ItemPropertyInfo
        CooldownReductionOnCatch: ItemPropertyInfo
        CooldownReductionOnHit: ItemPropertyInfo
        CooldownReductionOnHitNonHero: ItemPropertyInfo
        CooldownReductionOnKill: ItemPropertyInfo
        CooldownRefreshChancePercent: ItemPropertyInfo
        CooldownRefundPercent: ItemPropertyInfo
        CopiedUltWindow: ItemPropertyInfo
        CopyCooldownPercentage: ItemPropertyInfo
        CopyInternalCooldown: ItemPropertyInfo
        CrackshotNPCCDReduction: ItemPropertyInfo
        CreepDPS: ItemPropertyInfo
        CritBuildup: ItemPropertyInfo
        CubeScale: ItemPropertyInfo
        CurrentHealthDamage: ItemPropertyInfo
        CurrentHealthPercent: ItemPropertyInfo
        CurrentHealthPercentDamage: ItemPropertyInfo
        CurseDuration: ItemPropertyInfo
        DaggerCount: ItemPropertyInfo
        DaggersPerRow: ItemPropertyInfo
        DaggerSpreadAngle: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageAmplification: ItemPropertyInfo
        DamageAmplificationPerStack: ItemPropertyInfo
        DamageAmpPercentage: ItemPropertyInfo
        DamageBonus: ItemPropertyInfo
        DamageBonusFixedPerStack: ItemPropertyInfo
        DamageCooldown: ItemPropertyInfo
        DamageDisplay: ItemPropertyInfo
        DamageHealMult: ItemPropertyInfo
        DamageHealMultNonHero: ItemPropertyInfo
        DamageHeavyMelee: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamageInterval: ItemPropertyInfo
        DamageMax_DistanceFuzz: ItemPropertyInfo
        DamageMax: ItemPropertyInfo
        DamageMin: ItemPropertyInfo
        DamageOnBuildup: ItemPropertyInfo
        DamagePctDeferred: ItemPropertyInfo
        DamagePctDeferredMaxRage: ItemPropertyInfo
        DamagePctPerWallHit: ItemPropertyInfo
        DamagePercentHealth: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DamagePerDagger: ItemPropertyInfo
        DamagePerProjectile: ItemPropertyInfo
        DamagePerRocket: ItemPropertyInfo
        DamagePerSecond: ItemPropertyInfo
        DamagePerSecondFlown: ItemPropertyInfo
        DamagePerShot: ItemPropertyInfo
        DamageRadius: ItemPropertyInfo
        DamageTick: ItemPropertyInfo
        DamageTickRate: ItemPropertyInfo
        DamageVulnerbility: ItemPropertyInfo
        DamageWallHit: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DashAirSpeed: ItemPropertyInfo
        DashAngleThreshold: ItemPropertyInfo
        DashDistance: ItemPropertyInfo
        DashRadius: ItemPropertyInfo
        DashRange: ItemPropertyInfo
        DashSpeed: ItemPropertyInfo
        DeathTaxHeal: ItemPropertyInfo
        DebuffDelay: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DebuffMaxDuration: ItemPropertyInfo
        DebuffMinDuration: ItemPropertyInfo
        DecayingResist: ItemPropertyInfo
        DecayingResistDuration: ItemPropertyInfo
        DeferClearPct: ItemPropertyInfo
        DeferredDamageDuration: ItemPropertyInfo
        DelayBetweenDaggers: ItemPropertyInfo
        DelayBetweenShots: ItemPropertyInfo
        DemonShotCount: ItemPropertyInfo
        DetachBuffDuration: ItemPropertyInfo
        DetonateCooldown: ItemPropertyInfo
        DetonateTimer: ItemPropertyInfo
        DetonationDelay: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DisarmTargets: ItemPropertyInfo
        DismountHorizontalMaxSpeedPercent: ItemPropertyInfo
        DismountHorizontalMinSpeedPercent: ItemPropertyInfo
        DismountVerticalSpeed: ItemPropertyInfo
        Distance: ItemPropertyInfo
        DistanceAboveGround: ItemPropertyInfo
        DistanceOut: ItemPropertyInfo
        DistanceToMaxTime: ItemPropertyInfo
        DoesNotBreakInvis: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DoublePounceTime: ItemPropertyInfo
        DPS: ItemPropertyInfo
        DPSPercentHealth: ItemPropertyInfo
        DragReleaseSpeed: ItemPropertyInfo
        DropDownRate: ItemPropertyInfo
        DropOffTimer: ItemPropertyInfo
        Duration: ItemPropertyInfo
        EdgePushDuration: ItemPropertyInfo
        EMPEnemies: ItemPropertyInfo
        EmpoweredAttackCount: ItemPropertyInfo
        EndingSoonTime: ItemPropertyInfo
        EndJumpVelocity: ItemPropertyInfo
        EndOfHookMoveSpeedBonus: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        EnemyDamageSpeedPenalty: ItemPropertyInfo
        EnemyDragSpeed: ItemPropertyInfo
        EnemyHealthPercent: ItemPropertyInfo
        EnemyHealthPercentBuffer: ItemPropertyInfo
        EnemyHeroTossVelocity: ItemPropertyInfo
        EnemyLiftDuration: ItemPropertyInfo
        EnemyMinHealthPct: ItemPropertyInfo
        EnemyMoveSlow: ItemPropertyInfo
        EnemyMoveSlowDuration: ItemPropertyInfo
        EnemyShoveForce: ItemPropertyInfo
        EnemySlowDuration: ItemPropertyInfo
        EnemySlowPct: ItemPropertyInfo
        EscapeRange: ItemPropertyInfo
        EscapeTime: ItemPropertyInfo
        EvasionChance: ItemPropertyInfo
        EvasionPercent: ItemPropertyInfo
        ExecuteThreshold: ItemPropertyInfo
        ExitVelocity: ItemPropertyInfo
        ExpandTime: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeDebuffDuration: ItemPropertyInfo
        ExplodeDelay: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionFalloffDisabled: ItemPropertyInfo
        ExplosionPushForce: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        ExplosiveDamage: ItemPropertyInfo
        ExternalBonusHealthRegen: ItemPropertyInfo
        ExtraLargeClip: ItemPropertyInfo
        ExtraTargetConeAngle: ItemPropertyInfo
        ExtraTargetHorizontalOffset: ItemPropertyInfo
        FadingSlowPercent: ItemPropertyInfo
        FallSpeedMax: ItemPropertyInfo
        FastFireBullets: ItemPropertyInfo
        FireDPS: ItemPropertyInfo
        FireDuration: ItemPropertyInfo
        FireRadius: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRateBonusDurationMax: ItemPropertyInfo
        FireRateBuffDuration: ItemPropertyInfo
        FireRateMaxDuration: ItemPropertyInfo
        FireRateMultiplier: ItemPropertyInfo
        FireRatePerStack: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FireTickRate: ItemPropertyInfo
        FixedMoveSpeed: ItemPropertyInfo
        FlameAuraRadius: ItemPropertyInfo
        FlameDashJumpBonus: ItemPropertyInfo
        FlatBulletDamageReduction: ItemPropertyInfo
        FlatHealthHealing: ItemPropertyInfo
        FlightControlEnabled: ItemPropertyInfo
        FlyingBulletResist: ItemPropertyInfo
        FollowDampingFactor: ItemPropertyInfo
        FollowDistance: ItemPropertyInfo
        ForceFieldThinkRate: ItemPropertyInfo
        ForceReductionOnAngleDown: ItemPropertyInfo
        ForwardVelocity: ItemPropertyInfo
        Friction: ItemPropertyInfo
        FrictionPercentage: ItemPropertyInfo
        FriendlyBulletDamageBonus: ItemPropertyInfo
        FriendlyBulletTimeScale: ItemPropertyInfo
        FriendlyHookIgnoreRange: ItemPropertyInfo
        FullChargeDamage: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        FuseTime: ItemPropertyInfo
        FxRadius: ItemPropertyInfo
        GangsterHealth: ItemPropertyInfo
        GarbageRadius: ItemPropertyInfo
        GrabDamage: ItemPropertyInfo
        GrabExtraTargets: ItemPropertyInfo
        GrabExtraTargetsRadiusMult: ItemPropertyInfo
        GrabRange: ItemPropertyInfo
        GravityScale: ItemPropertyInfo
        GrenadeAngleVariance: ItemPropertyInfo
        GrenadeCount: ItemPropertyInfo
        GrenadesInVolley: ItemPropertyInfo
        GrenadesPerSecond: ItemPropertyInfo
        GrenadesPerSecondMult: ItemPropertyInfo
        GrenadeSpreadAngle: ItemPropertyInfo
        GroundAuraSpacing: ItemPropertyInfo
        GroundDashIncreasePercent: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GroundFlameDuration: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        GrowTime: ItemPropertyInfo
        HalfHeight: ItemPropertyInfo
        HangTime: ItemPropertyInfo
        HasDisarm: ItemPropertyInfo
        HeadshotBonus: ItemPropertyInfo
        Heal_Players_Post_Lane: ItemPropertyInfo
        Heal_Players: ItemPropertyInfo
        Heal_Troopers: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealFixedHealth: ItemPropertyInfo
        HealingFactor: ItemPropertyInfo
        HealingPerGlub: ItemPropertyInfo
        HealingPerSecond: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealMaxHealth: ItemPropertyInfo
        HealMaxHealthPercent: ItemPropertyInfo
        HealOnCloneDamage: ItemPropertyInfo
        HealPctVsHeroes: ItemPropertyInfo
        HealPctVsNonHeroes: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthRegen: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HealthStealPct: ItemPropertyInfo
        HealthStealPctHero: ItemPropertyInfo
        HealthToDamage: ItemPropertyInfo
        HeatDissipationInterval: ItemPropertyInfo
        HeatGrowthInterval: ItemPropertyInfo
        HeatPerAmmo: ItemPropertyInfo
        HeatPowerLength: ItemPropertyInfo
        HeavyMeleeForce: ItemPropertyInfo
        Height: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        HeightOffset: ItemPropertyInfo
        HeroNearbyRange: ItemPropertyInfo
        HeroStack: ItemPropertyInfo
        HexDuration: ItemPropertyInfo
        HexMoveSpeedLimit: ItemPropertyInfo
        HitSpeed: ItemPropertyInfo
        HoldDistance: ItemPropertyInfo
        HoldHeight: ItemPropertyInfo
        HoldInPlaceDuration: ItemPropertyInfo
        HookImpactDelay: ItemPropertyInfo
        HookingSlowSpeedLimit: ItemPropertyInfo
        HotDPS: ItemPropertyInfo
        HPOnHealthSteal: ItemPropertyInfo
        IceBeamBuildupProcDuration: ItemPropertyInfo
        IcePathAuraDuration: ItemPropertyInfo
        IcePathEdgeWidth: ItemPropertyInfo
        IcePathInterval: ItemPropertyInfo
        IcePathPullInStrength: ItemPropertyInfo
        IcePathShardRadius: ItemPropertyInfo
        IgnoreChannelSlow: ItemPropertyInfo
        ImmobilizeDuration: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactDuration: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        ImpactInterval: ItemPropertyInfo
        ImpactRadius: ItemPropertyInfo
        ImpactRadiusPercentage: ItemPropertyInfo
        ImpulseStrength: ItemPropertyInfo
        IncomingBulletDamagePercentFromCaster: ItemPropertyInfo
        IncomingDamagePercent: ItemPropertyInfo
        IncomingDamagePercentFromCaster: ItemPropertyInfo
        IncomingDamagePercentOnHit: ItemPropertyInfo
        InitialDamage: ItemPropertyInfo
        InitialDelay: ItemPropertyInfo
        InitialForce: ItemPropertyInfo
        InitialFreezeTime: ItemPropertyInfo
        InitialHeight: ItemPropertyInfo
        InitialProjectileVelocity: ItemPropertyInfo
        InitialRadius: ItemPropertyInfo
        InitialUpSpeed: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        InterruptCooldown: ItemPropertyInfo
        Interval: ItemPropertyInfo
        IntervalRampUpStart: ItemPropertyInfo
        IntervalRampUpTime: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisibilityDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        Invulnerable: ItemPropertyInfo
        JuggleAirSpeedMax: ItemPropertyInfo
        JuggleFallSpeedMax: ItemPropertyInfo
        JumpForce: ItemPropertyInfo
        JumpHeight: ItemPropertyInfo
        JumpPitch: ItemPropertyInfo
        JumpSlowResistance: ItemPropertyInfo
        JumpSpeed: ItemPropertyInfo
        JumpVelocity: ItemPropertyInfo
        KillCheckWindow: ItemPropertyInfo
        KillDuration: ItemPropertyInfo
        KnightChargeRange: ItemPropertyInfo
        KnightChargeWidth: ItemPropertyInfo
        KnightCount: ItemPropertyInfo
        KnightPositionSpread: ItemPropertyInfo
        KnightWhiskerLength: ItemPropertyInfo
        KnightWhiskerSide: ItemPropertyInfo
        KnightWhiskerStrength: ItemPropertyInfo
        KnockbackSpeed: ItemPropertyInfo
        KnockedOffDamagePct: ItemPropertyInfo
        KnockForce: ItemPropertyInfo
        LandingBonusesDuration: ItemPropertyInfo
        LandingDamage: ItemPropertyInfo
        LashFriendlies: ItemPropertyInfo
        LashMetalSkinDuration: ItemPropertyInfo
        LassoTargetMaxSpeed: ItemPropertyInfo
        LatchEndSpeed: ItemPropertyInfo
        LatchInitialSpeed: ItemPropertyInfo
        LatchReelAcc: ItemPropertyInfo
        LatchSpeed: ItemPropertyInfo
        LatchVisualSnapProgress: ItemPropertyInfo
        LaunchFalloff: ItemPropertyInfo
        LaunchMaxSpeed: ItemPropertyInfo
        LaunchMinSpeed: ItemPropertyInfo
        LaunchMinVerticalAmount: ItemPropertyInfo
        LaunchVerticalBias: ItemPropertyInfo
        LaunchWindowCooldown: ItemPropertyInfo
        LaunchWindowDuration: ItemPropertyInfo
        LeashRadius: ItemPropertyInfo
        LifeDrainHealthMult: ItemPropertyInfo
        LifeDrainPerSecond: ItemPropertyInfo
        LifestealHealthMult: ItemPropertyInfo
        LifestealPercent: ItemPropertyInfo
        LifestealPercentHero: ItemPropertyInfo
        LifeStealPercentOnHit: ItemPropertyInfo
        LifeStealPercentOnHitNonHero: ItemPropertyInfo
        LifestealPerSecond: ItemPropertyInfo
        LifestealTickRate: ItemPropertyInfo
        Lifetime: ItemPropertyInfo
        LiftChainCount: ItemPropertyInfo
        LiftChainRadius: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LiftHorizontal: ItemPropertyInfo
        LiftInitialDelay: ItemPropertyInfo
        LiftInitialRisingSpeed: ItemPropertyInfo
        LiftInitialVelocityEnd: ItemPropertyInfo
        LiftInitialVelocityStart: ItemPropertyInfo
        LiftTime: ItemPropertyInfo
        LightMeleeForce: ItemPropertyInfo
        LightningStrikeDamage: ItemPropertyInfo
        LightningStrikeDelay: ItemPropertyInfo
        LightningStrikeKnockBackForce: ItemPropertyInfo
        LightningStrikeRadius: ItemPropertyInfo
        LightningStrikes: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LockonConeAngle: ItemPropertyInfo
        LookDotMin: ItemPropertyInfo
        LookRadiusScale: ItemPropertyInfo
        LosingLockGraceTime: ItemPropertyInfo
        LowHealthEnemyDamageBonus: ItemPropertyInfo
        LowHealthEnemyThresholdPct: ItemPropertyInfo
        LowHealthHealingScalePercent: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MageTime: ItemPropertyInfo
        MagicDamagePerBullet: ItemPropertyInfo
        MakeInvisible: ItemPropertyInfo
        MarkDuration: ItemPropertyInfo
        MaxBonusBulletDamage: ItemPropertyInfo
        MaxBounces: ItemPropertyInfo
        MaxCameraAngleForSeeing: ItemPropertyInfo
        MaxChargeDuration: ItemPropertyInfo
        MaxChargeTime: ItemPropertyInfo
        MaxCooldownReductionsFromHits: ItemPropertyInfo
        MaxDaggers: ItemPropertyInfo
        MaxDamage: ItemPropertyInfo
        MaxDamageTime: ItemPropertyInfo
        MaxDeltaMovementControl: ItemPropertyInfo
        MaxDPS: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxFireRateSlowPercent: ItemPropertyInfo
        MaxFlyHeight: ItemPropertyInfo
        MaxGroundDashReduction: ItemPropertyInfo
        MaxGroundDashReductionPercent: ItemPropertyInfo
        MaxHealthHealOnCast: ItemPropertyInfo
        MaxHealthRegen: ItemPropertyInfo
        MaxHealthRegenPct: ItemPropertyInfo
        MaxHeatPower: ItemPropertyInfo
        MaxHPDPS: ItemPropertyInfo
        MaxLifetime: ItemPropertyInfo
        MaxLockonStacks: ItemPropertyInfo
        MaxMountDistance2D: ItemPropertyInfo
        MaxMoveSpeed: ItemPropertyInfo
        MaxPitch: ItemPropertyInfo
        MaxPlaneDistance: ItemPropertyInfo
        MaxPushVelocity: ItemPropertyInfo
        MaxRange: ItemPropertyInfo
        MaxRecasts: ItemPropertyInfo
        MaxRicochet: ItemPropertyInfo
        MaxSlow: ItemPropertyInfo
        MaxSlowDuration: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxSlowTime: ItemPropertyInfo
        MaxSoundDistance: ItemPropertyInfo
        MaxSpread: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MaxWallToWallDistance: ItemPropertyInfo
        MediumChargeDamagePct: ItemPropertyInfo
        MeleeAttackLength: ItemPropertyInfo
        MeleeAttackSpeedBonus: ItemPropertyInfo
        MeleeBurnDPS: ItemPropertyInfo
        MeleeDamageTakenScale: ItemPropertyInfo
        MeleeEMP: ItemPropertyInfo
        MeleeHalfAngle: ItemPropertyInfo
        MeleeHitCount: ItemPropertyInfo
        MeleeIgniteTime: ItemPropertyInfo
        MeleeRadius: ItemPropertyInfo
        MeleeSpeedBonusPercentage: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinAirTimeForStomp: ItemPropertyInfo
        MinBonusBulletDamage: ItemPropertyInfo
        MinChargeDamagePercent: ItemPropertyInfo
        MinDamage: ItemPropertyInfo
        MinDiffToCast: ItemPropertyInfo
        MinDistance: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        MinHealthTakenPct: ItemPropertyInfo
        MinHeight: ItemPropertyInfo
        MinimumSleepTime: ItemPropertyInfo
        MinRange: ItemPropertyInfo
        MinReflectionDOTResult: ItemPropertyInfo
        MinReflectionZ: ItemPropertyInfo
        MinShockDuration: ItemPropertyInfo
        MinSlowAmount: ItemPropertyInfo
        MinSlowDuration: ItemPropertyInfo
        MinSlowPercent: ItemPropertyInfo
        MinSpeed: ItemPropertyInfo
        MinSwapTime: ItemPropertyInfo
        MinTimeBeforeDestroy: ItemPropertyInfo
        MinTimeToTarget: ItemPropertyInfo
        MinVelocityZ: ItemPropertyInfo
        MinWallToWallDistance: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        ModifierRadius: ItemPropertyInfo
        MovementSlow: ItemPropertyInfo
        MovementSlowDuration: ItemPropertyInfo
        MovementSlowPct: ItemPropertyInfo
        MovementSpeedBonus: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MovementSpeedWhileShoot: ItemPropertyInfo
        MovementSpeedWhileZoom: ItemPropertyInfo
        MoveSlowDuration: ItemPropertyInfo
        MoveSlowPercent: ItemPropertyInfo
        MoveSpeed: ItemPropertyInfo
        MoveSpeedBonus: ItemPropertyInfo
        MoveSpeedBonusPct: ItemPropertyInfo
        MoveSpeedBonusPercentEnd: ItemPropertyInfo
        MoveSpeedBonusPercentStart: ItemPropertyInfo
        MoveSpeedGroundSlow: ItemPropertyInfo
        MoveSpeedLimit: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveSpeedMod: ItemPropertyInfo
        MoveSpeedPenaltyDuration: ItemPropertyInfo
        MoveSpeedPenaltyMaxSpeed: ItemPropertyInfo
        MoveSpeedPenaltyPerStack: ItemPropertyInfo
        MoveSpeedReduction: ItemPropertyInfo
        MoveSpeedSlowPct: ItemPropertyInfo
        MoveSpeedSlowPercent: ItemPropertyInfo
        MoveSpeedToTarget: ItemPropertyInfo
        MoveSpeedWhileShootingPenaltyReduction: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        MultiChain: ItemPropertyInfo
        MultiHitPenaltyPercentage: ItemPropertyInfo
        NoChannel: ItemPropertyInfo
        NoClipDuration: ItemPropertyInfo
        NonHeroDamagePercentOutgoing: ItemPropertyInfo
        NonHeroHealingFactor: ItemPropertyInfo
        NonHeroStack: ItemPropertyInfo
        NonLatchedDurationPct: ItemPropertyInfo
        NonPlayerCardResourceScale: ItemPropertyInfo
        NonPlayerRageScale: ItemPropertyInfo
        NormalDPS: ItemPropertyInfo
        NotInConeLosesLock: ItemPropertyInfo
        NotSeenByEnemiesRegen: ItemPropertyInfo
        NumBloodShards: ItemPropertyInfo
        NumWallSegments: ItemPropertyInfo
        OnLandDamageRadius: ItemPropertyInfo
        OnLandDamageRadiusStart: ItemPropertyInfo
        OpenHeight: ItemPropertyInfo
        OuterDamage: ItemPropertyInfo
        OutgoingDamage: ItemPropertyInfo
        OutgoingDamagePercent: ItemPropertyInfo
        OutgoingDamagePercentHungry: ItemPropertyInfo
        OutgoingProjectileLifetime: ItemPropertyInfo
        OutgoingTechDamagePercent: ItemPropertyInfo
        OverheatWarning: ItemPropertyInfo
        OverrideBulletRadius: ItemPropertyInfo
        ParriedStunTime: ItemPropertyInfo
        ParryMoveSpeed: ItemPropertyInfo
        ParticleRadiusMultiplier: ItemPropertyInfo
        PathLength: ItemPropertyInfo
        PathWidth: ItemPropertyInfo
        PauseOnTargetTime: ItemPropertyInfo
        PeakFireRateBonus: ItemPropertyInfo
        PercentHealthHealing: ItemPropertyInfo
        PetrifyDamage: ItemPropertyInfo
        PetrifyDamageBreakThreshold: ItemPropertyInfo
        PetrifyDuration: ItemPropertyInfo
        PhaseOutDuration: ItemPropertyInfo
        PlaceDistance: ItemPropertyInfo
        PlaneSpread: ItemPropertyInfo
        PlayerSpeedCheckScale: ItemPropertyInfo
        PopupForce: ItemPropertyInfo
        PopUpSpeed: ItemPropertyInfo
        PostCastHoldTime: ItemPropertyInfo
        PostCubeBuff: ItemPropertyInfo
        PostCubeBuffDuration: ItemPropertyInfo
        PostDashMaintainedVelocityRatio: ItemPropertyInfo
        PostInvisBuffDuration: ItemPropertyInfo
        PowerUpStages: ItemPropertyInfo
        PreDetonateDuration: ItemPropertyInfo
        PrepareTime: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        ProcDamage: ItemPropertyInfo
        ProcDamageBase: ItemPropertyInfo
        ProcDamagePercentage: ItemPropertyInfo
        ProcDamageStackCount: ItemPropertyInfo
        ProcMaxRange: ItemPropertyInfo
        ProjectileAmount: ItemPropertyInfo
        ProjectileArrivalTime: ItemPropertyInfo
        ProjectileFlyOutTime: ItemPropertyInfo
        ProjectileFlyReturnTime: ItemPropertyInfo
        ProjectileForwardSpeed: ItemPropertyInfo
        ProjectileHorizontalMinOffset: ItemPropertyInfo
        ProjectileIgnoreCollisionTime: ItemPropertyInfo
        ProjectileLifetime: ItemPropertyInfo
        ProjectileOffset: ItemPropertyInfo
        ProjectileOriginHeightOffset: ItemPropertyInfo
        ProjectileRedirectCount: ItemPropertyInfo
        ProjectileRowOffset: ItemPropertyInfo
        ProjectileSideFrequency: ItemPropertyInfo
        ProjectileSideSpeed: ItemPropertyInfo
        ProjectileThinkInterval: ItemPropertyInfo
        ProjectileTimeScale: ItemPropertyInfo
        PuddleDuration: ItemPropertyInfo
        PullSpeed: ItemPropertyInfo
        PullTargetSpeed: ItemPropertyInfo
        PulseDamage: ItemPropertyInfo
        PulseDPS: ItemPropertyInfo
        PulseInterval: ItemPropertyInfo
        PunchHalfHeight: ItemPropertyInfo
        PunchRollSlow: ItemPropertyInfo
        PunchRollSlowDuration: ItemPropertyInfo
        PurgeDebuffs: ItemPropertyInfo
        PurgeOnActivate: ItemPropertyInfo
        PurgeOnUse: ItemPropertyInfo
        PushAccel: ItemPropertyInfo
        PushBackDistance: ItemPropertyInfo
        PushBackForce: ItemPropertyInfo
        PushBackRadius: ItemPropertyInfo
        PushForce: ItemPropertyInfo
        PushNPCSpeed: ItemPropertyInfo
        PushSpeedMax: ItemPropertyInfo
        PushSpeedMid: ItemPropertyInfo
        PushSpeedMin: ItemPropertyInfo
        PushVelocity: ItemPropertyInfo
        Radius: ItemPropertyInfo
        RadiusGrowthTime: ItemPropertyInfo
        RadiusIncreasePerPulse: ItemPropertyInfo
        RadiusPerSecond: ItemPropertyInfo
        RageDrainDelayDuration: ItemPropertyInfo
        RageDrainRate: ItemPropertyInfo
        RagePerHeavyMelee: ItemPropertyInfo
        RagePerLightMelee: ItemPropertyInfo
        RagePerSpiritDamage: ItemPropertyInfo
        RagePerWeaponDamage: ItemPropertyInfo
        Range: ItemPropertyInfo
        RecastWindow: ItemPropertyInfo
        RecentDamageMarkDuration: ItemPropertyInfo
        RedirectVelocity: ItemPropertyInfo
        ReelSpeed: ItemPropertyInfo
        ReflectionSpeedFactor: ItemPropertyInfo
        RegenDamageInterval: ItemPropertyInfo
        RegenIncomingDamageDuration: ItemPropertyInfo
        RegenIncomingDamagePercent: ItemPropertyInfo
        ResetCooldownOnFriendlyHook: ItemPropertyInfo
        ResistancePerStack: ItemPropertyInfo
        ResourcePerCard: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RestoreHookCooldown: ItemPropertyInfo
        RestoreStaminaOnUse: ItemPropertyInfo
        RestrictionDuration: ItemPropertyInfo
        ReturnDamage: ItemPropertyInfo
        ReturnOffSetTargetDistance: ItemPropertyInfo
        ReturnRadius: ItemPropertyInfo
        ReturnUpVelocity: ItemPropertyInfo
        ReturnVelocity: ItemPropertyInfo
        RevealDuration: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        ReverseLifeLeech: ItemPropertyInfo
        ReverseLifeLeechDuration: ItemPropertyInfo
        RicochetAssistRatio: ItemPropertyInfo
        RicochetChance: ItemPropertyInfo
        RicochetCount: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        SalvageBonus_FireRate: ItemPropertyInfo
        SalvageBonus_Health: ItemPropertyInfo
        SalvageDuration: ItemPropertyInfo
        Scale: ItemPropertyInfo
        ScrapDamage: ItemPropertyInfo
        SearchAngle: ItemPropertyInfo
        SearchRadius: ItemPropertyInfo
        SearchRate: ItemPropertyInfo
        SecondaryHealHeroRange: ItemPropertyInfo
        SecondDoorPlacementWindow: ItemPropertyInfo
        SecondHit: ItemPropertyInfo
        SecondHitDamagePercentage: ItemPropertyInfo
        SegmentEmitTime: ItemPropertyInfo
        SelfBuffDuration: ItemPropertyInfo
        SelfBumpImpulse: ItemPropertyInfo
        SelfDamage: ItemPropertyInfo
        SelfDamagePct: ItemPropertyInfo
        SelfDamagePercent: ItemPropertyInfo
        SelfDPS: ItemPropertyInfo
        SelfLaunchPercent: ItemPropertyInfo
        SelfShoveForce: ItemPropertyInfo
        SenseRange: ItemPropertyInfo
        ShadowFormDurationOnKill: ItemPropertyInfo
        ShareDamagePercent: ItemPropertyInfo
        ShareDamageThreshold: ItemPropertyInfo
        ShareWithFriendsRadius: ItemPropertyInfo
        ShieldDuration: ItemPropertyInfo
        ShockDelay: ItemPropertyInfo
        ShockRadius: ItemPropertyInfo
        ShootDelay: ItemPropertyInfo
        ShootDuration: ItemPropertyInfo
        ShootInterval: ItemPropertyInfo
        ShortChargeDamagePct: ItemPropertyInfo
        ShortCooldown: ItemPropertyInfo
        ShotCount: ItemPropertyInfo
        ShotRadius: ItemPropertyInfo
        ShotsToProc: ItemPropertyInfo
        ShouldBounce: ItemPropertyInfo
        SideMoveSpeedReduction: ItemPropertyInfo
        Silence: ItemPropertyInfo
        SilenceBombSpeed: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SilenceOnDrain: ItemPropertyInfo
        SilenceOnHeavyDuration: ItemPropertyInfo
        SilenceRadius: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlamSpeed: ItemPropertyInfo
        SlashCollisionRadius: ItemPropertyInfo
        SlashForwardOffset: ItemPropertyInfo
        SlashHeight: ItemPropertyInfo
        SlashLength: ItemPropertyInfo
        SlashRadius: ItemPropertyInfo
        SlashRange: ItemPropertyInfo
        SleepDuration: ItemPropertyInfo
        SleepMoveSpeed: ItemPropertyInfo
        SleepWakeUpDelay: ItemPropertyInfo
        SlideForce: ItemPropertyInfo
        SlideLeapSpeedPenaltyMax: ItemPropertyInfo
        SlideLeapSpeedPenaltyTime: ItemPropertyInfo
        SlideResist: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowDurationPerStack: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistance: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SlowTargetDuration: ItemPropertyInfo
        SmokeDuration: ItemPropertyInfo
        SpawnDuration: ItemPropertyInfo
        Speed: ItemPropertyInfo
        SpeedBoostDuration: ItemPropertyInfo
        SpeedBurstDuration: ItemPropertyInfo
        SpeedBurstSpeed: ItemPropertyInfo
        SpeedChange: ItemPropertyInfo
        SpeedInitial: ItemPropertyInfo
        SpeedLostDuration: ItemPropertyInfo
        SpeedOnLand: ItemPropertyInfo
        SpeedOnLandDuration: ItemPropertyInfo
        SpellLifesteal: ItemPropertyInfo
        SpherePushExtraDistance: ItemPropertyInfo
        SphereRadius: ItemPropertyInfo
        SpiderArmingTime: ItemPropertyInfo
        SpiderChaseVelocity: ItemPropertyInfo
        SpiderClimbHeight: ItemPropertyInfo
        SpiderCount: ItemPropertyInfo
        SpiderDamage: ItemPropertyInfo
        SpiderDistAboveGround: ItemPropertyInfo
        SpiderExplodeRadius: ItemPropertyInfo
        SpiderFloatDownRate: ItemPropertyInfo
        SpiderGravity: ItemPropertyInfo
        SpiderLifetime: ItemPropertyInfo
        SpiderRandomPositionRadius: ItemPropertyInfo
        SpiderSearchRadius: ItemPropertyInfo
        SpiderTickRate: ItemPropertyInfo
        SpinDuration: ItemPropertyInfo
        SpinSlowDuration: ItemPropertyInfo
        SpinSlowPercent: ItemPropertyInfo
        SpiritReducedPerStack: ItemPropertyInfo
        SpiritResReducedPerStack: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SplitAngle: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngle: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDistance: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        SpreadRadius: ItemPropertyInfo
        SpreadTargets: ItemPropertyInfo
        SprintSpeedBonus: ItemPropertyInfo
        StackDuration: ItemPropertyInfo
        StacksCanDecay: ItemPropertyInfo
        StageDuration: ItemPropertyInfo
        StageRadius: ItemPropertyInfo
        StakeCount: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownIncrease: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StaminaHeal: ItemPropertyInfo
        StaminaHungry: ItemPropertyInfo
        StaminaRecoveryDisabledDuration: ItemPropertyInfo
        StaminaRecoveryReduction: ItemPropertyInfo
        StaminaReduction: ItemPropertyInfo
        StandStillMinTime: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StatStealDamageInstances: ItemPropertyInfo
        StatStealDuration: ItemPropertyInfo
        StatueArmTime: ItemPropertyInfo
        StatueHealth: ItemPropertyInfo
        StatueScale: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StompBounceHeight: ItemPropertyInfo
        StompDamage: ItemPropertyInfo
        StompDamagePerMeterPrimary: ItemPropertyInfo
        StompDamagePerMeterSecondary: ItemPropertyInfo
        StompDamagePrimaryRange: ItemPropertyInfo
        StompRange: ItemPropertyInfo
        StompStunDuration: ItemPropertyInfo
        StompVerticalThreshold: ItemPropertyInfo
        StompWidth: ItemPropertyInfo
        StrikeVelocity: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        StunOnLand: ItemPropertyInfo
        StunsTargets: ItemPropertyInfo
        StunTargetOnExplode: ItemPropertyInfo
        SummonCasterHealthPct: ItemPropertyInfo
        SummonCount: ItemPropertyInfo
        SummonDPS: ItemPropertyInfo
        SummonHealth: ItemPropertyInfo
        SummonLifetime: ItemPropertyInfo
        SummonMoveSpeed: ItemPropertyInfo
        SwapEndDelay: ItemPropertyInfo
        SwapTime: ItemPropertyInfo
        SwapTotalDamage: ItemPropertyInfo
        SweepSpeed: ItemPropertyInfo
        SwingLineBulletDistance: ItemPropertyInfo
        TackleRadius: ItemPropertyInfo
        TackleSpeed: ItemPropertyInfo
        TargetBounceCount: ItemPropertyInfo
        TargetBounceRange: ItemPropertyInfo
        TargetBulletEvasionChance: ItemPropertyInfo
        TargetingConeAngle: ItemPropertyInfo
        TargetingDuration: ItemPropertyInfo
        TargetingWidth: ItemPropertyInfo
        TargetLifesteal: ItemPropertyInfo
        TargetLifestealNonHero: ItemPropertyInfo
        TargetLingerDuration: ItemPropertyInfo
        TargetOffSetScale: ItemPropertyInfo
        TargetPracticeDuration: ItemPropertyInfo
        TargetsPerTick: ItemPropertyInfo
        TechAmpLinger: ItemPropertyInfo
        TechAmpPerBullet: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechCleaveExpireTime: ItemPropertyInfo
        TechLifestealPercent: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechPowerAmpBonus: ItemPropertyInfo
        TechPowerAmpBonusDuration: ItemPropertyInfo
        TechPowerAmpBonusMaxStacks: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TechResistDebuff: ItemPropertyInfo
        TechShield: ItemPropertyInfo
        TechShieldDuration: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherLength: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        TetherSharedHealPct: ItemPropertyInfo
        ThinkInterval: ItemPropertyInfo
        ThirdHitDamagePercentage: ItemPropertyInfo
        ThrowDamage: ItemPropertyInfo
        ThrowDistance: ItemPropertyInfo
        ThrownObjectRadius: ItemPropertyInfo
        ThrowSpeed: ItemPropertyInfo
        ThrowStraightDuration: ItemPropertyInfo
        TickInterval: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TickTime: ItemPropertyInfo
        TimeBeforeCursed: ItemPropertyInfo
        TimeBeforeProjectileLaunch: ItemPropertyInfo
        TimeBetweenGrenades: ItemPropertyInfo
        TimeBetweenSegments: ItemPropertyInfo
        TimeBetweenShots: ItemPropertyInfo
        TimeScaleDebuff: ItemPropertyInfo
        TimeScaleDuration: ItemPropertyInfo
        TimeToFullCharge: ItemPropertyInfo
        TimeToGainLockonStack: ItemPropertyInfo
        TimeToLoseLockonStack: ItemPropertyInfo
        TimeToMaxDistance: ItemPropertyInfo
        TimeUntilStasis: ItemPropertyInfo
        TimeWallDepth: ItemPropertyInfo
        TimeWallDepthVisualScale: ItemPropertyInfo
        TimeWallFormationTime: ItemPropertyInfo
        TimeWallHeight: ItemPropertyInfo
        TimeWallTimeScale: ItemPropertyInfo
        TimeWallWidth: ItemPropertyInfo
        TimeWarpRadius: ItemPropertyInfo
        ToggleOffDelay: ItemPropertyInfo
        TornadoSpeed: ItemPropertyInfo
        TossAngle: ItemPropertyInfo
        TossBackSpeed: ItemPropertyInfo
        TossGroundSideRatio: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TossSpeedUpWall: ItemPropertyInfo
        TossSpeedWall: ItemPropertyInfo
        TossUpMagnitude: ItemPropertyInfo
        TossUpSpeed: ItemPropertyInfo
        TossVelocity: ItemPropertyInfo
        TotalBolts: ItemPropertyInfo
        TotalShotCount: ItemPropertyInfo
        TotalShots: ItemPropertyInfo
        TotalSwaps: ItemPropertyInfo
        TotalTetherTargets: ItemPropertyInfo
        TrackingDistance: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TrackingTime: ItemPropertyInfo
        TrackingVariance: ItemPropertyInfo
        TrackSpeedFar: ItemPropertyInfo
        TrackSpeedNear: ItemPropertyInfo
        TrailingTeamBonusSprintSpeed: ItemPropertyInfo
        TrailInterval: ItemPropertyInfo
        TrapHeight: ItemPropertyInfo
        TripGravity: ItemPropertyInfo
        TripTime: ItemPropertyInfo
        TripUpSpeed: ItemPropertyInfo
        TurnRateMax: ItemPropertyInfo
        TurnRateSlowDuration: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackFalloffEnd: ItemPropertyInfo
        TurretAttackFalloffStart: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretBaseHealth: ItemPropertyInfo
        TurretBulletTargetAngle: ItemPropertyInfo
        TurretBulletTargetRadius: ItemPropertyInfo
        TurretBulletVerticalOffset: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretDPS: ItemPropertyInfo
        TurretHealMult: ItemPropertyInfo
        TurretHealthPerBoon: ItemPropertyInfo
        TurretHealthScaling: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        UnstoppableCastDelay: ItemPropertyInfo
        UpBoostSpeed: ItemPropertyInfo
        UpFactor: ItemPropertyInfo
        UpForce: ItemPropertyInfo
        UpImpulse: ItemPropertyInfo
        UppercutBuffOnHit: ItemPropertyInfo
        UppercutDamage: ItemPropertyInfo
        UseHeavyMelee: ItemPropertyInfo
        VacuumRadius: ItemPropertyInfo
        VenomBuildupPerShot: ItemPropertyInfo
        VenomDuration: ItemPropertyInfo
        VenomMaxDamage: ItemPropertyInfo
        VenomMaxDamageHealthPercentage: ItemPropertyInfo
        VenomMinDamage: ItemPropertyInfo
        VenomMinDamageHealthPercentage: ItemPropertyInfo
        VenomMissingHealthDamagePercentage: ItemPropertyInfo
        VentEfficiency: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        VerticalSpeed: ItemPropertyInfo
        VictimDamageReduction: ItemPropertyInfo
        VictimDamageTakenScale: ItemPropertyInfo
        VictimPushTime: ItemPropertyInfo
        VictimStackDuration: ItemPropertyInfo
        ViewPunch: ItemPropertyInfo
        VisibilityTime: ItemPropertyInfo
        VisualSplashRadius: ItemPropertyInfo
        VolleyInterval: ItemPropertyInfo
        VulnerabilityPerStack: ItemPropertyInfo
        WallImpactLookAheadDistance: ItemPropertyInfo
        WallImpactRange: ItemPropertyInfo
        WallLatchIdealDist: ItemPropertyInfo
        WallLatchSettleDist: ItemPropertyInfo
        WallLatchSettleTime: ItemPropertyInfo
        WallStunDuration: ItemPropertyInfo
        WeaponDamageBonus: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponDamageBonusPerSec: ItemPropertyInfo
        WeaponDamagePerHeat: ItemPropertyInfo
        WeaponDamageScale: ItemPropertyInfo
        WeaponFireRateBonus: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
        WeaponPowerBuffDuration: ItemPropertyInfo
        WeaponPowerDebuff: ItemPropertyInfo
        WeaponPowerIncreaseDuration: ItemPropertyInfo
        WeaponReadyDuration: ItemPropertyInfo
        WeaponRecoilReduction: ItemPropertyInfo
        WeaponSpreadPenalty: ItemPropertyInfo
        WebArmTime: ItemPropertyInfo
        WebDuration: ItemPropertyInfo
        WebWallTickRate: ItemPropertyInfo
        WhirlwindDuration: ItemPropertyInfo
        WhirlwindEvasionChance: ItemPropertyInfo
        WreckingBallDamage: ItemPropertyInfo
        WreckingBallPushForce: ItemPropertyInfo
        ZipAcc: ItemPropertyInfo
        ZiplineProtectionDamageAmp: ItemPropertyInfo
        ZiplineProtectionSlowDurationOnHit: ItemPropertyInfo
        ZipSpeedInner: ItemPropertyInfo
        ZipSpeedOuter: ItemPropertyInfo
        ZoomBias: ItemPropertyInfo
        ZoomTime: ItemPropertyInfo
    }
`;
