export const upgradeTypeDefs = `
    type UpgradeItem implements Item {
        activation: String
        class_name: String!
        cost: Int
        description: ItemDescription
        disabled: Boolean
        hero: Hero
        heroes: [Hero]
        id: ID!
        image_webp: String
        image: String
        is_active_item: Boolean
        item_slot_type: String
        item_tier: Int
        name: String
        properties: UpgradeItemProperties
        shop_image_small_webp: String
        shop_image_small: String
        shop_image_webp: String
        shop_image: String
        shopable: Boolean
        start_trained: Boolean
        tooltip_sections: [TooltipSection]
        type: String
        update_time: Int
        weapon_info: UpgradeItemWeaponInfo
    }

    type UpgradeItemWeaponInfo implements ItemWeaponInfo {
        bullet_speed_curve: BulletSpeedCurve
    }

    type UpgradeItemProperties implements ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityChargeUpTime: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityLifestealPercentHero: ItemPropertyInfo
        AbilityLifestealPercentHeroPassive: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        ActivatedFireRate: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActiveBonusFireRate: ItemPropertyInfo
        ActiveBonusLifesteal: ItemPropertyInfo
        ActiveBonusMoveSpeed: ItemPropertyInfo
        ActiveMoveSpeedPenalty: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirJumps: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        AmbushBonusFireRate: ItemPropertyInfo
        AmbushBonusMeleeDamage: ItemPropertyInfo
        AmbushBonusTechPower: ItemPropertyInfo
        AmbushDuration: ItemPropertyInfo
        AmmoPerSoul: ItemPropertyInfo
        AmmoReloadPercent: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        ArmorLossPerHit: ItemPropertyInfo
        AssaultDuration: ItemPropertyInfo
        AssaultFireRate: ItemPropertyInfo
        AssaultLifestealPercent: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        AuraRadius: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BaseAttackDamagePercentAtMaxDuration: ItemPropertyInfo
        BaseAttackDamagePercentBonus: ItemPropertyInfo
        BaseBonusCounter: ItemPropertyInfo
        BaseBonusWeaponPower: ItemPropertyInfo
        BaseDamagePct: ItemPropertyInfo
        BaseDamagePerShot: ItemPropertyInfo
        BonusAbilityCharges: ItemPropertyInfo
        BonusAbilityDurationPercent: ItemPropertyInfo
        BonusAttackRangePercent: ItemPropertyInfo
        BonusBulletSpeedPercent: ItemPropertyInfo
        BonusChargedAbilityDamage: ItemPropertyInfo
        BonusChargedCooldownReduction: ItemPropertyInfo
        BonusClipPerKill: ItemPropertyInfo
        BonusClipSize: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusDamagePerHero: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusFireRateNPC: ItemPropertyInfo
        BonusHeadshotDamage: ItemPropertyInfo
        BonusHealth: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusHeavyMeleeDamage: ItemPropertyInfo
        BonusMeleeDamagePercent: ItemPropertyInfo
        BonusMovespeed: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusReloadSpeed: ItemPropertyInfo
        BonusReloadTime: ItemPropertyInfo
        BonusShotsDuration: ItemPropertyInfo
        BonusSoulsPct: ItemPropertyInfo
        BonusSpirit: ItemPropertyInfo
        BonusSpiritForChargedAbilities: ItemPropertyInfo
        BonusSpiritMaxTime: ItemPropertyInfo
        BonusSpiritMin: ItemPropertyInfo
        BonusSpiritWindow: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BonusWeaponPower: ItemPropertyInfo
        BonusZoomPercent: ItemPropertyInfo
        BuffBulletResist: ItemPropertyInfo
        BuffDamageMult: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuffMeleeDamageBoost: ItemPropertyInfo
        BuffMoveSpeedBonus: ItemPropertyInfo
        BuffTechResist: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BulletArmor: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletDamageReflectedPct: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletProcDeflectionPercent: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistBelowThreshold: ItemPropertyInfo
        BulletResistDuration: ItemPropertyInfo
        BulletResistPerStack: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletsBonusMagicDamage: ItemPropertyInfo
        BulletShieldDamagePercent: ItemPropertyInfo
        BulletShieldMaxHealth: ItemPropertyInfo
        BulletSpeedOverride: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        BurstFireShotPercent: ItemPropertyInfo
        BurstFireShotsFromClipPercent: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        CasterBuffDuration: ItemPropertyInfo
        CasterHealthPercent: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        CooldownBetweenChargeReduction: ItemPropertyInfo
        CooldownOnMiss: ItemPropertyInfo
        CooldownReduction: ItemPropertyInfo
        CooldownReductionFlat: ItemPropertyInfo
        CooldownReductionOnChargedAbilities: ItemPropertyInfo
        CooldownReductionPctOnNonHeroes: ItemPropertyInfo
        CooldownReductionPctOnOthers: ItemPropertyInfo
        CooldownReductionPerHit: ItemPropertyInfo
        CritDamagePercent: ItemPropertyInfo
        CycleTimeFireRateDecrease: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageDuration: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamagePctVsNonHeroes: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DamagePulseAmount: ItemPropertyInfo
        DamagePulseRadius: ItemPropertyInfo
        DamageReduction: ItemPropertyInfo
        DamageThreshold: ItemPropertyInfo
        DamageThresholdDuration: ItemPropertyInfo
        DamageToStack: ItemPropertyInfo
        DamageWindow: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DeathImmunityDamageReduction: ItemPropertyInfo
        DeathImmunityDuration: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DebuffRadius: ItemPropertyInfo
        DeflectionPercent: ItemPropertyInfo
        DeflectionRandomness: ItemPropertyInfo
        DegenResistance: ItemPropertyInfo
        DelayBeforeStun: ItemPropertyInfo
        DelayDuration: ItemPropertyInfo
        DiminishingMultiplier: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DotDuration: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DotMultiplerTroopers: ItemPropertyInfo
        DPS: ItemPropertyInfo
        DPSIncrease: ItemPropertyInfo
        DPSMax: ItemPropertyInfo
        DropDownSpeed: ItemPropertyInfo
        EMPDuration: ItemPropertyInfo
        EMPProcChance: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        EnemyLifeThreshold: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        FervorFireRate: ItemPropertyInfo
        FervorMovespeed: ItemPropertyInfo
        FervorTechResist: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRatePerKill: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FireRateSlowDuration: ItemPropertyInfo
        FlyMoveSpeed: ItemPropertyInfo
        FreezeDuration: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        GalvanicBuffDuration: ItemPropertyInfo
        GalvanicDebuffDuration: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        GuardianWardCombatBarrier: ItemPropertyInfo
        HeadShotBonusDamage: ItemPropertyInfo
        HeadshotBonusSteal: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpCastPercent: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealAmpRegenPercent: ItemPropertyInfo
        HealFromHero: ItemPropertyInfo
        HealFromNPC: ItemPropertyInfo
        HealingPerCast: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealLifePercentOutOfCombat: ItemPropertyInfo
        HealOnActivate: ItemPropertyInfo
        HealOnKill: ItemPropertyInfo
        HealOnLevelHealAmount: ItemPropertyInfo
        HealOnSuccess: ItemPropertyInfo
        HealOnVeil: ItemPropertyInfo
        HealPercentAmount: ItemPropertyInfo
        HealPercentPerHeadshot: ItemPropertyInfo
        HealPerStack: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthDamagePercent: ItemPropertyInfo
        HealthDrainedPerSecond: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HealthThreshold: ItemPropertyInfo
        HeavyMeleeMultiplier: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        HeroMultiplier: ItemPropertyInfo
        HeroTargetBonus: ItemPropertyInfo
        HighGroundBonusWeaponPower: ItemPropertyInfo
        ImbuedBonusDamage: ItemPropertyInfo
        ImbuedBonusDuration: ItemPropertyInfo
        ImbuedTechPower: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        InitialFireRateDecrease: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        InteruptCooldown: ItemPropertyInfo
        Interval: ItemPropertyInfo
        IntraBurstFireRateIncrease: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisDuration: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        ItemCooldownReduction: ItemPropertyInfo
        JumpVelocityHidden: ItemPropertyInfo
        KillBonusMoveSpeedPerStack: ItemPropertyInfo
        KillWindow: ItemPropertyInfo
        LifestealHeal: ItemPropertyInfo
        LifestealHealPercent: ItemPropertyInfo
        LifestrikeHeal: ItemPropertyInfo
        LifestrikeHealPercent: ItemPropertyInfo
        LifeThreshold: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LightMeleeAmmo: ItemPropertyInfo
        LightMeleeCooldownMult: ItemPropertyInfo
        LightMeleeStacks: ItemPropertyInfo
        LightMeleeTimeWindow: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LocalBulletArmorReduction: ItemPropertyInfo
        LongRangeBonusWeaponPower: ItemPropertyInfo
        LongRangeBonusWeaponPowerMinRange: ItemPropertyInfo
        LowHealthLifeStealPercent: ItemPropertyInfo
        LowHealthPercentThreshold: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MagicIncreasePerStack: ItemPropertyInfo
        MagicResistReduction: ItemPropertyInfo
        MaxArmorStacks: ItemPropertyInfo
        MaxBonusDuration: ItemPropertyInfo
        MaxBulletResist: ItemPropertyInfo
        MaxClipBonus: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxFireRateIncrease: ItemPropertyInfo
        MaxHealthDamage: ItemPropertyInfo
        MaxHealthLossPercent: ItemPropertyInfo
        MaxHealthPercentAsDPS: ItemPropertyInfo
        MaxHeightForBonus: ItemPropertyInfo
        MaxKillBonusMoveSpeedStack: ItemPropertyInfo
        MaxLandingSpeed: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MaxWeaponPower: ItemPropertyInfo
        MeleeDistanceScale: ItemPropertyInfo
        MeleeResistPercent: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        MinimumDamage: ItemPropertyInfo
        MinimumHealAmount: ItemPropertyInfo
        MinTargetsRequired: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        ModelScaleGrowth: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MovementThresholdSq: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        NanoTechPerShot: ItemPropertyInfo
        NonBurstFireConversionFactor: ItemPropertyInfo
        NonHeroAbilityLifestealTooltipOnly: ItemPropertyInfo
        NonHeroHealPct: ItemPropertyInfo
        NonHeroMult: ItemPropertyInfo
        NonHeroReductionPercent: ItemPropertyInfo
        NonPlayerBonusWeaponPower: ItemPropertyInfo
        NonPlayerBulletResist: ItemPropertyInfo
        NormalizedClipEmptySpeedIncrease: ItemPropertyInfo
        NPCDamageMult: ItemPropertyInfo
        OutgoingDamagePenaltyPercent: ItemPropertyInfo
        OutOfCombatHealthRegen: ItemPropertyInfo
        OverdriveClipDuration: ItemPropertyInfo
        ParryCooldownReduction: ItemPropertyInfo
        ParrySuccessHealPercentage: ItemPropertyInfo
        ParticleRadius: ItemPropertyInfo
        PercentDamage: ItemPropertyInfo
        PerfectBurstWeaponPower: ItemPropertyInfo
        ProcAmmoConsumed: ItemPropertyInfo
        ProcBaseAttackDamagePercent: ItemPropertyInfo
        ProcBaseAttackDamagePercentAltFire: ItemPropertyInfo
        ProcBonusMagicDamage: ItemPropertyInfo
        ProcBulletVelocity: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        Radius: ItemPropertyInfo
        ReduceFootstepSound: ItemPropertyInfo
        RegenDuration: ItemPropertyInfo
        Regeneration: ItemPropertyInfo
        RegenerationDuration: ItemPropertyInfo
        RegenWhileInvisible: ItemPropertyInfo
        ReloadSpeedMultipler: ItemPropertyInfo
        ReProcLockoutTime: ItemPropertyInfo
        ResistReduction: ItemPropertyInfo
        ResistReductionDuration: ItemPropertyInfo
        RespawnBonusHealthDuration: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RestoreDelay: ItemPropertyInfo
        ReturnFireBulletResist: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        RicochetTargetsTooltipOnly: ItemPropertyInfo
        SelfModifier: ItemPropertyInfo
        ShootDurationForMax: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SingleTargetPlayerMultiplier: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlamDownRadius: ItemPropertyInfo
        SlamdownSpeed: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SpawnTimePenalty: ItemPropertyInfo
        SpecialShotsBonusFireRate: ItemPropertyInfo
        SpellAmplificationMultiplier: ItemPropertyInfo
        SpellParryDuration: ItemPropertyInfo
        SpellShieldFlavorText: ItemPropertyInfo
        SpellShieldLingerDuration: ItemPropertyInfo
        SpinUpDecay: ItemPropertyInfo
        SpinUpTime: ItemPropertyInfo
        SpiritDamage: ItemPropertyInfo
        SpiritDamageReductionProc: ItemPropertyInfo
        SpiritDamageReflectedPct: ItemPropertyInfo
        SpiritPower: ItemPropertyInfo
        SpiritPowerInnate: ItemPropertyInfo
        SpiritPowerPerSoul: ItemPropertyInfo
        SpiritSteal: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SpiritStolePerHit: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        StackingBonusHealth: ItemPropertyInfo
        StackingBonusSprintSpeed: ItemPropertyInfo
        StackingGoldPerMinute: ItemPropertyInfo
        StackingTechRadiusMultiplier: ItemPropertyInfo
        StackingTechRangeMultiplier: ItemPropertyInfo
        StackLossFrequency: ItemPropertyInfo
        StackLostPerDeath: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StaminaToRestore: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StasisRadius: ItemPropertyInfo
        StationaryRecoilReduction: ItemPropertyInfo
        StationaryWeaponPower: ItemPropertyInfo
        StatusResistancePercent: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StealPerHit: ItemPropertyInfo
        StealPerKill: ItemPropertyInfo
        StoredSpiritDamage: ItemPropertyInfo
        StunDelay: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        SummonDuration: ItemPropertyInfo
        TechArmor: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechArmorGain: ItemPropertyInfo
        TechCleaveDamagePercent: ItemPropertyInfo
        TechCleaveRadius: ItemPropertyInfo
        TechDamagePercent: ItemPropertyInfo
        TechDamageReduction: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechPowerGain: ItemPropertyInfo
        TechPowerPercent: ItemPropertyInfo
        TechPowerReduction: ItemPropertyInfo
        TechRadiusMultiplier: ItemPropertyInfo
        TechRadiusMultiplierBuff: ItemPropertyInfo
        TechRangeMultiplier: ItemPropertyInfo
        TechRangeMultiplierBuff: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TechResistBelowThreshold: ItemPropertyInfo
        TechShieldMaxHealth: ItemPropertyInfo
        TempTechShieldHealth: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        ThinkRate: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TotalHealthRegen: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        VexBarrierCombatBarrier: ItemPropertyInfo
        VisualContractRadius: ItemPropertyInfo
        WatcherMaxDuration: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponDamagePerStack: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
        WeaponPowerPerDeath: ItemPropertyInfo
        WeaponPowerPerKill: ItemPropertyInfo
        WeaponPowerPerStack: ItemPropertyInfo
        WeaponPowerWhileActivated: ItemPropertyInfo
    }

    type TooltipSection {
        section_type: String
        section_attributes: [ToolTipSectionAttributes]
    }

    type ToolTipSectionAttributes {
        loc_string: String
        properties: [String]
        important_properties: [String]
    }
`;
