export const weaponTypeDefs = `
    type WeaponItem implements Item {
        class_name: String!
        description: ItemDescription
        hero: Hero
        heroes: [Hero]
        id: ID!
        image_webp: String
        image: String
        name: String
        properties: WeaponItemProperties
        start_trained: Boolean
        type: String
        update_time: Int
        weapon_info: WeaponItemWeaponInfo
    }

    type WeaponItemProperties implements ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletsConsumedForMax: ItemPropertyInfo
        BulletsPerDegree: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        ChargeParticleMaxScale: ItemPropertyInfo
        ChargeTime: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DamageRadiusMax: ItemPropertyInfo
        DamageRadiusMin: ItemPropertyInfo
        DamageScaleBias: ItemPropertyInfo
        DamageScaleMax: ItemPropertyInfo
        DamageScaleMin: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DelayAfterChargeShot: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DPS: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        Interval: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MaxBonusDamagePercent: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxRotation: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        MinRotation: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        NoWindUpTime: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        ProjectileRadiusMax: ItemPropertyInfo
        PushForceOffGround: ItemPropertyInfo
        PushForceOnGround: ItemPropertyInfo
        Radius: ItemPropertyInfo
        RefreshDuration: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        ShootDirectionDelay: ItemPropertyInfo
        ShootPositionRandomRadius: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlideVelocity: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        StackThreshold: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TimeBetweenBulletConsume: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        UpPushForce: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
        WindUpSpread: ItemPropertyInfo
        WindUpTime: ItemPropertyInfo
    }

    type WeaponItemWeaponInfo implements ItemWeaponInfo {
        aiming_shot_spread_penalty: [Float]
        bullet_damage: Float
        bullet_gravity_scale: Float
        bullet_inherit_shooter_velocity_scale: Float
        bullet_lifetime: Float
        bullet_radius_vs_world: Float
        bullet_radius: Float
        bullet_reflect_amount: Float
        bullet_reflect_scale: Float
        bullet_speed_curve: BulletSpeedCurve
        bullet_whiz_distance: Float
        bullets: Float
        burst_shot_cooldown: Float
        burst_shot_count: Float
        can_zoom: Boolean
        clip_size: Float
        crit_bonus_end_range: Float
        crit_bonus_end: Float
        crit_bonus_start_range: Float
        crit_bonus_start: Float
        cycle_time: Float
        damage_falloff_bias: Float
        damage_falloff_end_range: Float
        damage_falloff_end_scale: Float
        damage_falloff_start_range: Float
        damage_falloff_start_scale: Float
        horizontal_punch: Float
        horizontal_recoil: HorizontalRecoil
        intra_burst_cycle_time: Float
        max_spin_cycle_time: Float
        range: Float
        recoil_recovery_delay_factor: Float
        recoil_recovery_speed: Float
        recoil_shot_index_recovery_time_factor: Float
        recoil_speed: Float
        reload_duration: Float
        reload_move_speed: Float
        scatter_yaw_scale: Float
        shoot_move_speed_percent: Float
        shoot_spread_penalty_decay_delay: Float
        shoot_spread_penalty_decay: Float
        shoot_spread_penalty_per_shot: Float
        shooting_up_spread_penalty: Float
        standing_shot_spread_penalty: [Float]
        vertical_punch: Float
        zoom_move_speed_percent: Float
    }

    type BulletSpeedCurve {
        spline: [Spline]
        domain_maxs: [Float]
        domain_mins: [Float]
    }

    type Spline {
        slope_incoming: Float
        slope_outgoing: Float
        x: Float
        y: Float
    }

    type HorizontalRecoil {
        range: [Float]
        burst_exponent: Float
    }
`;
