const typeDefs: string = `
    type Query {
        hero(id: ID, name: String, class_name: String): Hero
        heroes(limit: Int, offset: Int): [Hero]
        item( id: ID, name: String, class_name: String): Item
        items(itemType: String, limit: Int, offset: Int): [Item]
    }

    interface Item {
        id: ID!
        class_name: String!
        name: String
        start_trained: Boolean
        image: String
        image_webp: String
        hero: Hero
        heroes: [Hero]
        type: String
        description: ItemDescription
        update_time: Int
    }

    interface ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DPS: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        Interval: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        Radius: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
    }

    type ItemPropertyInfo {
        can_set_token_override: Boolean
        css_class: String
        disable_value: String
        display_units: String
        icon: String
        label: String
        postfix: String
        prefix: String
        provided_property_type: String
        scale_function: ScaleFunction
        usage_flags: [String]
        value: String
    }

    type ScaleFunction {
        class_name: String
        subclass_name: String
        specific_stat_scale_type: String
    }

    type ItemDescription {
        desc: String
        quip: String
        t1_desc: String
        t2_desc: String
        t3_desc: String
    }

    interface ItemWeaponInfo {
        bullet_speed_curve: BulletSpeedCurve
    }

    type WeaponItem implements Item {
        class_name: String!
        description: ItemDescription
        hero: Hero
        heroes: [Hero]
        id: ID!
        image_webp: String
        image: String
        name: String
        properties: WeaponItemProperties
        start_trained: Boolean
        type: String
        update_time: Int
        weapon_info: WeaponItemWeaponInfo
    }

    type WeaponItemProperties implements ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletsConsumedForMax: ItemPropertyInfo
        BulletsPerDegree: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        ChargeParticleMaxScale: ItemPropertyInfo
        ChargeTime: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DamageRadiusMax: ItemPropertyInfo
        DamageRadiusMin: ItemPropertyInfo
        DamageScaleBias: ItemPropertyInfo
        DamageScaleMax: ItemPropertyInfo
        DamageScaleMin: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DelayAfterChargeShot: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DPS: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        Interval: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MaxBonusDamagePercent: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxRotation: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        MinRotation: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        NoWindUpTime: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        ProjectileRadiusMax: ItemPropertyInfo
        PushForceOffGround: ItemPropertyInfo
        PushForceOnGround: ItemPropertyInfo
        Radius: ItemPropertyInfo
        RefreshDuration: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        ShootDirectionDelay: ItemPropertyInfo
        ShootPositionRandomRadius: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlideVelocity: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        StackThreshold: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TimeBetweenBulletConsume: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        UpPushForce: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
        WindUpSpread: ItemPropertyInfo
        WindUpTime: ItemPropertyInfo
    }

    type WeaponItemWeaponInfo implements ItemWeaponInfo {
        aiming_shot_spread_penalty: [Float]
        bullet_damage: Float
        bullet_gravity_scale: Float
        bullet_inherit_shooter_velocity_scale: Float
        bullet_lifetime: Float
        bullet_radius_vs_world: Float
        bullet_radius: Float
        bullet_reflect_amount: Float
        bullet_reflect_scale: Float
        bullet_speed_curve: BulletSpeedCurve
        bullet_whiz_distance: Float
        bullets: Float
        burst_shot_cooldown: Float
        burst_shot_count: Float
        can_zoom: Boolean
        clip_size: Float
        crit_bonus_end_range: Float
        crit_bonus_end: Float
        crit_bonus_start_range: Float
        crit_bonus_start: Float
        cycle_time: Float
        damage_falloff_bias: Float
        damage_falloff_end_range: Float
        damage_falloff_end_scale: Float
        damage_falloff_start_range: Float
        damage_falloff_start_scale: Float
        horizontal_punch: Float
        horizontal_recoil: HorizontalRecoil
        intra_burst_cycle_time: Float
        max_spin_cycle_time: Float
        range: Float
        recoil_recovery_delay_factor: Float
        recoil_recovery_speed: Float
        recoil_shot_index_recovery_time_factor: Float
        recoil_speed: Float
        reload_duration: Float
        reload_move_speed: Float
        scatter_yaw_scale: Float
        shoot_move_speed_percent: Float
        shoot_spread_penalty_decay_delay: Float
        shoot_spread_penalty_decay: Float
        shoot_spread_penalty_per_shot: Float
        shooting_up_spread_penalty: Float
        standing_shot_spread_penalty: [Float]
        vertical_punch: Float
        zoom_move_speed_percent: Float
    }

    type BulletSpeedCurve {
        spline: [Spline]
        domain_maxs: [Float]
        domain_mins: [Float]
    }

    type Spline {
        slope_incoming: Float
        slope_outgoing: Float
        x: Float
        y: Float
    }

    type HorizontalRecoil {
        range: [Float]
        burst_exponent: Float
    }

    type AbilityItem implements Item {
        ability_type: String
        behaviours: [String]
        boss_damage_scale: Float
        class_name: String!
        dependant_abilities: [String]
        description: ItemDescription
        hero: Hero
        heroes: [Hero]
        id: ID!
        image_webp: String
        image: String
        name: String
        properties: AbilityItemProperties
        start_trained: Boolean
        tooltip_details: ToolTipDetails
        type: String
        update_time: Int
        upgrades: [AbilityItemUpgrade]
        videos: Videos
        weapon_info: AbilityItemWeaponInfo
    }

    type AbilityItemWeaponInfo implements ItemWeaponInfo {
        bullet_speed_curve: BulletSpeedCurve
    }

    type Videos {
        webm: String
        mp4: String
    }

    type ToolTipDetails {
        info_sections: [InfoSection]
    }

    type InfoSection {
        loc_string: String
        property_upgrade_required: String
        properties_block: [InfoSectionPropertiesBlock]
        basic_properties: [String]
    }

    type InfoSectionPropertiesBlock {
        properties: [PropertiesBlockProperties]
    }

    type PropertiesBlockProperties {
        important_property_icon: String
        important_property: String
        requires_ability_upgrade: Boolean
        show_property_value: Boolean
        status_effect_name: String
        status_effect_value: String
    }

    type AbilityItemUpgrade {
        name: String
        bonus: String
    }

    type AbilityItemProperties implements ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityChannelTimeDisplay: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityChargesConditionally: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityCooldownPerHeadshot: ItemPropertyInfo
        AbilityCooldownPerHeadshotNPC: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityLifestealPercent: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilitySpeedPct: ItemPropertyInfo
        AbilitySplitShot: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        AccelerationPercentage: ItemPropertyInfo
        AccelSpeed: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActivationDistance: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AdditionalShockTarget: ItemPropertyInfo
        AfterburnSpiritDamageReduction: ItemPropertyInfo
        AimFOV: ItemPropertyInfo
        AimZoomDuration: ItemPropertyInfo
        AirControlAccelPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirDampingDuration: ItemPropertyInfo
        AirDrag: ItemPropertyInfo
        AirDropBulletShield: ItemPropertyInfo
        AirJumpForce: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        AirSideMoveSpeedPercentage: ItemPropertyInfo
        AirSpeedBonus: ItemPropertyInfo
        AirSpeedMax: ItemPropertyInfo
        AlliedFireRatePercentage: ItemPropertyInfo
        AllowMovement: ItemPropertyInfo
        AllyCastDelay: ItemPropertyInfo
        AllyDistance: ItemPropertyInfo
        AllyHeight: ItemPropertyInfo
        AllyOutgoingDamagePercent: ItemPropertyInfo
        AllyRadius: ItemPropertyInfo
        AltJumpSpeed: ItemPropertyInfo
        AmpDuration: ItemPropertyInfo
        AmpPercentPerStack: ItemPropertyInfo
        AOERadius: ItemPropertyInfo
        ArmingDuration: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        ArmTime: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        AttackRadius: ItemPropertyInfo
        AttackSpeedMult: ItemPropertyInfo
        AuraEffectDuration: ItemPropertyInfo
        AuraFireRateBonus: ItemPropertyInfo
        AuraLingerDuration: ItemPropertyInfo
        BackstabBonusDamagePct: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BackwardsVelocity: ItemPropertyInfo
        BallHitRadius: ItemPropertyInfo
        BallOffset: ItemPropertyInfo
        BallRadius: ItemPropertyInfo
        BarbedWireDamagePerMeter: ItemPropertyInfo
        BarbedWireDPS: ItemPropertyInfo
        BarbedWireHeightOffGround: ItemPropertyInfo
        BarbedWireRadius: ItemPropertyInfo
        BarbedWireSlow: ItemPropertyInfo
        BarbedWireTickRate: ItemPropertyInfo
        BarrelBounceVelocity: ItemPropertyInfo
        BarrelDamage: ItemPropertyInfo
        BarrelHeavyMeleeForceForward: ItemPropertyInfo
        BarrelHeavyMeleeForceUp: ItemPropertyInfo
        BarrelLifetime: ItemPropertyInfo
        BarrelLightMeleeForceForward: ItemPropertyInfo
        BarrelLightMeleeForceUp: ItemPropertyInfo
        BarrelPitchMax: ItemPropertyInfo
        BarrelPitchMin: ItemPropertyInfo
        BarrelRollSpeedMoveAir: ItemPropertyInfo
        BarrelRollSpeedMoveMin: ItemPropertyInfo
        BarrelScale: ItemPropertyInfo
        BarrelUpFactor: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BaseBulletDamage: ItemPropertyInfo
        BaseDamage: ItemPropertyInfo
        BaseHeatPower: ItemPropertyInfo
        BatCount: ItemPropertyInfo
        BatCountPerWave: ItemPropertyInfo
        BatSpawnRadius: ItemPropertyInfo
        BatSpawnRandomAngle: ItemPropertyInfo
        BatSpawnRandomVelocity: ItemPropertyInfo
        BeamCloseDamagePercent: ItemPropertyInfo
        BeamCloseRadius: ItemPropertyInfo
        BeamEndRadius: ItemPropertyInfo
        BeamLength: ItemPropertyInfo
        BeamLifesteal: ItemPropertyInfo
        BeamLifestealNonHeroPercent: ItemPropertyInfo
        BeamSplit: ItemPropertyInfo
        BeamSplitCount: ItemPropertyInfo
        BeamWidth: ItemPropertyInfo
        BeepSoundBuildupCount: ItemPropertyInfo
        BeepSoundIntervalBias: ItemPropertyInfo
        BeepSoundMaxFrequency: ItemPropertyInfo
        BlastJumpVelocity: ItemPropertyInfo
        BlastJumpVelocityCrouch: ItemPropertyInfo
        BlastJumpVelocityGround: ItemPropertyInfo
        BlastRadius: ItemPropertyInfo
        BleedDPSPerStack: ItemPropertyInfo
        BleedDuration: ItemPropertyInfo
        BleedTickRate: ItemPropertyInfo
        BlindScale: ItemPropertyInfo
        BlockerScaleFactor: ItemPropertyInfo
        BloodSpillDPSPercent: ItemPropertyInfo
        BloodSpillDuration: ItemPropertyInfo
        BoloBounceCount: ItemPropertyInfo
        BoloBounceSpeed: ItemPropertyInfo
        BoloContractRadius: ItemPropertyInfo
        BoloHitDamage: ItemPropertyInfo
        BoloProcDamage: ItemPropertyInfo
        BoloRadius: ItemPropertyInfo
        BoltRefundPerKill: ItemPropertyInfo
        BombFriction: ItemPropertyInfo
        BombRestitution: ItemPropertyInfo
        BonusAbilityResource: ItemPropertyInfo
        BonusBatsMax: ItemPropertyInfo
        BonusBatsPerProc: ItemPropertyInfo
        BonusBulletSpeed: ItemPropertyInfo
        BonusClip: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusCritDamagePercent: ItemPropertyInfo
        BonusDamage: ItemPropertyInfo
        BonusDamageCap: ItemPropertyInfo
        BonusDamageConversionPercent: ItemPropertyInfo
        BonusDamageDecayLockoutDuration: ItemPropertyInfo
        BonusDamageDecayPerSecond: ItemPropertyInfo
        BonusDamageDecayRate: ItemPropertyInfo
        BonusDamagePctPerPlayerHit: ItemPropertyInfo
        BonusDamagePctPerPlayerKilled: ItemPropertyInfo
        BonusDamagePerBullet: ItemPropertyInfo
        BonusDamagePercent: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusFireRatePerHero: ItemPropertyInfo
        BonusGoldOnKill: ItemPropertyInfo
        BonusHealthOnKill: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusKnockbackDistance: ItemPropertyInfo
        BonusMaxHealth: ItemPropertyInfo
        BonusMaxHealthPerHero: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusMoveSpeedPercent: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusPerHeadshot: ItemPropertyInfo
        BonusSpiritLingerDuration: ItemPropertyInfo
        BonusSpiritMax: ItemPropertyInfo
        BonusSpiritMeter: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BonusStamina: ItemPropertyInfo
        BonusTechDamagePercent: ItemPropertyInfo
        BonusTechPowerPerKill: ItemPropertyInfo
        BoostTime: ItemPropertyInfo
        BossDamagePercentIncoming: ItemPropertyInfo
        BossDamagePercentOutgoing: ItemPropertyInfo
        BouncePadExtendDuration: ItemPropertyInfo
        BounceRadians: ItemPropertyInfo
        BounceRange: ItemPropertyInfo
        BounceVelocity: ItemPropertyInfo
        BreakablePropDamageRadius: ItemPropertyInfo
        BreakoutTime: ItemPropertyInfo
        BuffBaseWeaponPct: ItemPropertyInfo
        BuffDamage: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuffGunRangePercent: ItemPropertyInfo
        BuffOnKillDuration: ItemPropertyInfo
        BuffTarget: ItemPropertyInfo
        BuildUpBulletPercentPerHit: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpMaxDamage: ItemPropertyInfo
        BuildUpMaxDamageNonHero: ItemPropertyInfo
        BuildUpPerBat: ItemPropertyInfo
        BuildUpPerDagger: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BuildupProcDamage: ItemPropertyInfo
        BuildupProcDuration: ItemPropertyInfo
        BuildupSpiritDamageThreshold: ItemPropertyInfo
        BulletAccuracy: ItemPropertyInfo
        BulletAmp: ItemPropertyInfo
        BulletAmpDuration: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletArmorReductionDuration: ItemPropertyInfo
        BulletArmorReductionHeavy: ItemPropertyInfo
        BulletArmorReductionLight: ItemPropertyInfo
        BulletDamageIncrease: ItemPropertyInfo
        BulletForce: ItemPropertyInfo
        BulletLifesteal: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletRadiusOverride: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistOnActive: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletResistReductionDuration: ItemPropertyInfo
        BulletScaleFactor: ItemPropertyInfo
        BulletShieldDamageConversionPercent: ItemPropertyInfo
        BulletShieldDuration: ItemPropertyInfo
        BulletShieldHealth: ItemPropertyInfo
        BulletShieldMaxHealthPercentage: ItemPropertyInfo
        BulletShieldMissingHealthPercentage: ItemPropertyInfo
        BulletShieldPerHero: ItemPropertyInfo
        BulletShieldPoints: ItemPropertyInfo
        BulletSpeedPercent: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        BulletTimeScale: ItemPropertyInfo
        BulletVulnerbility: ItemPropertyInfo
        BurnDuration: ItemPropertyInfo
        BurstBonusPerStack: ItemPropertyInfo
        CameraDistance: ItemPropertyInfo
        CameraHeightOffset: ItemPropertyInfo
        CameraHorizontalOffset: ItemPropertyInfo
        CameraPreviewDistance: ItemPropertyInfo
        CameraPreviewOffset: ItemPropertyInfo
        CameraPreviewSpeed: ItemPropertyInfo
        CameraTurnRateMax: ItemPropertyInfo
        CanBePurged: ItemPropertyInfo
        CancelHookDuration: ItemPropertyInfo
        CanGrappleAllyHeroes: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        CardResourceGenPctScale: ItemPropertyInfo
        CardResourcePerBulletCrit: ItemPropertyInfo
        CardResourcePerBulletHit: ItemPropertyInfo
        CardResourcePerHeavyMelee: ItemPropertyInfo
        CardResourcePerLightMelee: ItemPropertyInfo
        CastRangeWhenVertical: ItemPropertyInfo
        CastRangeWhenVerticalBias: ItemPropertyInfo
        CastWhileRolling: ItemPropertyInfo
        CatAboveGround: ItemPropertyInfo
        CatAccel: ItemPropertyInfo
        CatActivateDuration: ItemPropertyInfo
        CatchRadius: ItemPropertyInfo
        CatClimbHeight: ItemPropertyInfo
        CatDropDownRate: ItemPropertyInfo
        CatFormDamageDealtReduction: ItemPropertyInfo
        CatLifetime: ItemPropertyInfo
        CatMaxSpeed: ItemPropertyInfo
        CatStartSpeed: ItemPropertyInfo
        CenterDamage: ItemPropertyInfo
        CenterRadius: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainDuration: ItemPropertyInfo
        ChainLength: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        ChannelSlowPercent: ItemPropertyInfo
        ChannelTimeForMaxDebuff: ItemPropertyInfo
        ChargeDistance: ItemPropertyInfo
        ChargeDragVerticalOffset: ItemPropertyInfo
        ChargedShotHitRadiusScale: ItemPropertyInfo
        ChargeForKill: ItemPropertyInfo
        ChargeRadius: ItemPropertyInfo
        ChargeSpeedMax: ItemPropertyInfo
        ChargeUpTime: ItemPropertyInfo
        ClimbHeight: ItemPropertyInfo
        ClimbPerGrenade: ItemPropertyInfo
        ClipSizeBonus: ItemPropertyInfo
        ClipSizeOverride: ItemPropertyInfo
        CloneBoltDelay: ItemPropertyInfo
        CloneDamagePercentage: ItemPropertyInfo
        CloneDamageTakenIncreasePercent: ItemPropertyInfo
        CloneGoldToGive: ItemPropertyInfo
        CloneHealthPercentage: ItemPropertyInfo
        CloneLifetime: ItemPropertyInfo
        CloneSpawnDistance: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CloseRangeSpeed: ItemPropertyInfo
        CloudHeight: ItemPropertyInfo
        CollidePlayersStopTime: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        ConeAngle: ItemPropertyInfo
        ConeRadius: ItemPropertyInfo
        ConsumeHealPercentage: ItemPropertyInfo
        CooldownPerStack: ItemPropertyInfo
        CooldownReductionOnCatch: ItemPropertyInfo
        CooldownReductionOnHit: ItemPropertyInfo
        CooldownReductionOnHitNonHero: ItemPropertyInfo
        CooldownReductionOnKill: ItemPropertyInfo
        CooldownRefreshChancePercent: ItemPropertyInfo
        CooldownRefundPercent: ItemPropertyInfo
        CopiedUltWindow: ItemPropertyInfo
        CopyCooldownPercentage: ItemPropertyInfo
        CopyInternalCooldown: ItemPropertyInfo
        CrackshotNPCCDReduction: ItemPropertyInfo
        CreepDPS: ItemPropertyInfo
        CritBuildup: ItemPropertyInfo
        CubeScale: ItemPropertyInfo
        CurrentHealthDamage: ItemPropertyInfo
        CurrentHealthPercent: ItemPropertyInfo
        CurrentHealthPercentDamage: ItemPropertyInfo
        CurseDuration: ItemPropertyInfo
        DaggerCount: ItemPropertyInfo
        DaggersPerRow: ItemPropertyInfo
        DaggerSpreadAngle: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageAmplification: ItemPropertyInfo
        DamageAmplificationPerStack: ItemPropertyInfo
        DamageAmpPercentage: ItemPropertyInfo
        DamageBonus: ItemPropertyInfo
        DamageBonusFixedPerStack: ItemPropertyInfo
        DamageCooldown: ItemPropertyInfo
        DamageDisplay: ItemPropertyInfo
        DamageHealMult: ItemPropertyInfo
        DamageHealMultNonHero: ItemPropertyInfo
        DamageHeavyMelee: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamageInterval: ItemPropertyInfo
        DamageMax_DistanceFuzz: ItemPropertyInfo
        DamageMax: ItemPropertyInfo
        DamageMin: ItemPropertyInfo
        DamageOnBuildup: ItemPropertyInfo
        DamagePctDeferred: ItemPropertyInfo
        DamagePctDeferredMaxRage: ItemPropertyInfo
        DamagePctPerWallHit: ItemPropertyInfo
        DamagePercentHealth: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DamagePerDagger: ItemPropertyInfo
        DamagePerProjectile: ItemPropertyInfo
        DamagePerRocket: ItemPropertyInfo
        DamagePerSecond: ItemPropertyInfo
        DamagePerSecondFlown: ItemPropertyInfo
        DamagePerShot: ItemPropertyInfo
        DamageRadius: ItemPropertyInfo
        DamageTick: ItemPropertyInfo
        DamageTickRate: ItemPropertyInfo
        DamageVulnerbility: ItemPropertyInfo
        DamageWallHit: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DashAirSpeed: ItemPropertyInfo
        DashAngleThreshold: ItemPropertyInfo
        DashDistance: ItemPropertyInfo
        DashRadius: ItemPropertyInfo
        DashRange: ItemPropertyInfo
        DashSpeed: ItemPropertyInfo
        DeathTaxHeal: ItemPropertyInfo
        DebuffDelay: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DebuffMaxDuration: ItemPropertyInfo
        DebuffMinDuration: ItemPropertyInfo
        DecayingResist: ItemPropertyInfo
        DecayingResistDuration: ItemPropertyInfo
        DeferClearPct: ItemPropertyInfo
        DeferredDamageDuration: ItemPropertyInfo
        DelayBetweenDaggers: ItemPropertyInfo
        DelayBetweenShots: ItemPropertyInfo
        DemonShotCount: ItemPropertyInfo
        DetachBuffDuration: ItemPropertyInfo
        DetonateCooldown: ItemPropertyInfo
        DetonateTimer: ItemPropertyInfo
        DetonationDelay: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DisarmTargets: ItemPropertyInfo
        DismountHorizontalMaxSpeedPercent: ItemPropertyInfo
        DismountHorizontalMinSpeedPercent: ItemPropertyInfo
        DismountVerticalSpeed: ItemPropertyInfo
        Distance: ItemPropertyInfo
        DistanceAboveGround: ItemPropertyInfo
        DistanceOut: ItemPropertyInfo
        DistanceToMaxTime: ItemPropertyInfo
        DoesNotBreakInvis: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DoublePounceTime: ItemPropertyInfo
        DPS: ItemPropertyInfo
        DPSPercentHealth: ItemPropertyInfo
        DragReleaseSpeed: ItemPropertyInfo
        DropDownRate: ItemPropertyInfo
        DropOffTimer: ItemPropertyInfo
        Duration: ItemPropertyInfo
        EdgePushDuration: ItemPropertyInfo
        EMPEnemies: ItemPropertyInfo
        EmpoweredAttackCount: ItemPropertyInfo
        EndingSoonTime: ItemPropertyInfo
        EndJumpVelocity: ItemPropertyInfo
        EndOfHookMoveSpeedBonus: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        EnemyDamageSpeedPenalty: ItemPropertyInfo
        EnemyDragSpeed: ItemPropertyInfo
        EnemyHealthPercent: ItemPropertyInfo
        EnemyHealthPercentBuffer: ItemPropertyInfo
        EnemyHeroTossVelocity: ItemPropertyInfo
        EnemyLiftDuration: ItemPropertyInfo
        EnemyMinHealthPct: ItemPropertyInfo
        EnemyMoveSlow: ItemPropertyInfo
        EnemyMoveSlowDuration: ItemPropertyInfo
        EnemyShoveForce: ItemPropertyInfo
        EnemySlowDuration: ItemPropertyInfo
        EnemySlowPct: ItemPropertyInfo
        EscapeRange: ItemPropertyInfo
        EscapeTime: ItemPropertyInfo
        EvasionChance: ItemPropertyInfo
        EvasionPercent: ItemPropertyInfo
        ExecuteThreshold: ItemPropertyInfo
        ExitVelocity: ItemPropertyInfo
        ExpandTime: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeDebuffDuration: ItemPropertyInfo
        ExplodeDelay: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionFalloffDisabled: ItemPropertyInfo
        ExplosionPushForce: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        ExplosiveDamage: ItemPropertyInfo
        ExternalBonusHealthRegen: ItemPropertyInfo
        ExtraLargeClip: ItemPropertyInfo
        ExtraTargetConeAngle: ItemPropertyInfo
        ExtraTargetHorizontalOffset: ItemPropertyInfo
        FadingSlowPercent: ItemPropertyInfo
        FallSpeedMax: ItemPropertyInfo
        FastFireBullets: ItemPropertyInfo
        FireDPS: ItemPropertyInfo
        FireDuration: ItemPropertyInfo
        FireRadius: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRateBonusDurationMax: ItemPropertyInfo
        FireRateBuffDuration: ItemPropertyInfo
        FireRateMaxDuration: ItemPropertyInfo
        FireRateMultiplier: ItemPropertyInfo
        FireRatePerStack: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FireTickRate: ItemPropertyInfo
        FixedMoveSpeed: ItemPropertyInfo
        FlameAuraRadius: ItemPropertyInfo
        FlameDashJumpBonus: ItemPropertyInfo
        FlatBulletDamageReduction: ItemPropertyInfo
        FlatHealthHealing: ItemPropertyInfo
        FlightControlEnabled: ItemPropertyInfo
        FlyingBulletResist: ItemPropertyInfo
        FollowDampingFactor: ItemPropertyInfo
        FollowDistance: ItemPropertyInfo
        ForceFieldThinkRate: ItemPropertyInfo
        ForceReductionOnAngleDown: ItemPropertyInfo
        ForwardVelocity: ItemPropertyInfo
        Friction: ItemPropertyInfo
        FrictionPercentage: ItemPropertyInfo
        FriendlyBulletDamageBonus: ItemPropertyInfo
        FriendlyBulletTimeScale: ItemPropertyInfo
        FriendlyHookIgnoreRange: ItemPropertyInfo
        FullChargeDamage: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        FuseTime: ItemPropertyInfo
        FxRadius: ItemPropertyInfo
        GangsterHealth: ItemPropertyInfo
        GarbageRadius: ItemPropertyInfo
        GrabDamage: ItemPropertyInfo
        GrabExtraTargets: ItemPropertyInfo
        GrabExtraTargetsRadiusMult: ItemPropertyInfo
        GrabRange: ItemPropertyInfo
        GravityScale: ItemPropertyInfo
        GrenadeAngleVariance: ItemPropertyInfo
        GrenadeCount: ItemPropertyInfo
        GrenadesInVolley: ItemPropertyInfo
        GrenadesPerSecond: ItemPropertyInfo
        GrenadesPerSecondMult: ItemPropertyInfo
        GrenadeSpreadAngle: ItemPropertyInfo
        GroundAuraSpacing: ItemPropertyInfo
        GroundDashIncreasePercent: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GroundFlameDuration: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        GrowTime: ItemPropertyInfo
        HalfHeight: ItemPropertyInfo
        HangTime: ItemPropertyInfo
        HasDisarm: ItemPropertyInfo
        HeadshotBonus: ItemPropertyInfo
        Heal_Players_Post_Lane: ItemPropertyInfo
        Heal_Players: ItemPropertyInfo
        Heal_Troopers: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealFixedHealth: ItemPropertyInfo
        HealingFactor: ItemPropertyInfo
        HealingPerGlub: ItemPropertyInfo
        HealingPerSecond: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealMaxHealth: ItemPropertyInfo
        HealMaxHealthPercent: ItemPropertyInfo
        HealOnCloneDamage: ItemPropertyInfo
        HealPctVsHeroes: ItemPropertyInfo
        HealPctVsNonHeroes: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthRegen: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HealthStealPct: ItemPropertyInfo
        HealthStealPctHero: ItemPropertyInfo
        HealthToDamage: ItemPropertyInfo
        HeatDissipationInterval: ItemPropertyInfo
        HeatGrowthInterval: ItemPropertyInfo
        HeatPerAmmo: ItemPropertyInfo
        HeatPowerLength: ItemPropertyInfo
        HeavyMeleeForce: ItemPropertyInfo
        Height: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        HeightOffset: ItemPropertyInfo
        HeroNearbyRange: ItemPropertyInfo
        HeroStack: ItemPropertyInfo
        HexDuration: ItemPropertyInfo
        HexMoveSpeedLimit: ItemPropertyInfo
        HitSpeed: ItemPropertyInfo
        HoldDistance: ItemPropertyInfo
        HoldHeight: ItemPropertyInfo
        HoldInPlaceDuration: ItemPropertyInfo
        HookImpactDelay: ItemPropertyInfo
        HookingSlowSpeedLimit: ItemPropertyInfo
        HotDPS: ItemPropertyInfo
        HPOnHealthSteal: ItemPropertyInfo
        IceBeamBuildupProcDuration: ItemPropertyInfo
        IcePathAuraDuration: ItemPropertyInfo
        IcePathEdgeWidth: ItemPropertyInfo
        IcePathInterval: ItemPropertyInfo
        IcePathPullInStrength: ItemPropertyInfo
        IcePathShardRadius: ItemPropertyInfo
        IgnoreChannelSlow: ItemPropertyInfo
        ImmobilizeDuration: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactDuration: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        ImpactInterval: ItemPropertyInfo
        ImpactRadius: ItemPropertyInfo
        ImpactRadiusPercentage: ItemPropertyInfo
        ImpulseStrength: ItemPropertyInfo
        IncomingBulletDamagePercentFromCaster: ItemPropertyInfo
        IncomingDamagePercent: ItemPropertyInfo
        IncomingDamagePercentFromCaster: ItemPropertyInfo
        IncomingDamagePercentOnHit: ItemPropertyInfo
        InitialDamage: ItemPropertyInfo
        InitialDelay: ItemPropertyInfo
        InitialForce: ItemPropertyInfo
        InitialFreezeTime: ItemPropertyInfo
        InitialHeight: ItemPropertyInfo
        InitialProjectileVelocity: ItemPropertyInfo
        InitialRadius: ItemPropertyInfo
        InitialUpSpeed: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        InterruptCooldown: ItemPropertyInfo
        Interval: ItemPropertyInfo
        IntervalRampUpStart: ItemPropertyInfo
        IntervalRampUpTime: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisibilityDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        Invulnerable: ItemPropertyInfo
        JuggleAirSpeedMax: ItemPropertyInfo
        JuggleFallSpeedMax: ItemPropertyInfo
        JumpForce: ItemPropertyInfo
        JumpHeight: ItemPropertyInfo
        JumpPitch: ItemPropertyInfo
        JumpSlowResistance: ItemPropertyInfo
        JumpSpeed: ItemPropertyInfo
        JumpVelocity: ItemPropertyInfo
        KillCheckWindow: ItemPropertyInfo
        KillDuration: ItemPropertyInfo
        KnightChargeRange: ItemPropertyInfo
        KnightChargeWidth: ItemPropertyInfo
        KnightCount: ItemPropertyInfo
        KnightPositionSpread: ItemPropertyInfo
        KnightWhiskerLength: ItemPropertyInfo
        KnightWhiskerSide: ItemPropertyInfo
        KnightWhiskerStrength: ItemPropertyInfo
        KnockbackSpeed: ItemPropertyInfo
        KnockedOffDamagePct: ItemPropertyInfo
        KnockForce: ItemPropertyInfo
        LandingBonusesDuration: ItemPropertyInfo
        LandingDamage: ItemPropertyInfo
        LashFriendlies: ItemPropertyInfo
        LashMetalSkinDuration: ItemPropertyInfo
        LassoTargetMaxSpeed: ItemPropertyInfo
        LatchEndSpeed: ItemPropertyInfo
        LatchInitialSpeed: ItemPropertyInfo
        LatchReelAcc: ItemPropertyInfo
        LatchSpeed: ItemPropertyInfo
        LatchVisualSnapProgress: ItemPropertyInfo
        LaunchFalloff: ItemPropertyInfo
        LaunchMaxSpeed: ItemPropertyInfo
        LaunchMinSpeed: ItemPropertyInfo
        LaunchMinVerticalAmount: ItemPropertyInfo
        LaunchVerticalBias: ItemPropertyInfo
        LaunchWindowCooldown: ItemPropertyInfo
        LaunchWindowDuration: ItemPropertyInfo
        LeashRadius: ItemPropertyInfo
        LifeDrainHealthMult: ItemPropertyInfo
        LifeDrainPerSecond: ItemPropertyInfo
        LifestealHealthMult: ItemPropertyInfo
        LifestealPercent: ItemPropertyInfo
        LifestealPercentHero: ItemPropertyInfo
        LifeStealPercentOnHit: ItemPropertyInfo
        LifeStealPercentOnHitNonHero: ItemPropertyInfo
        LifestealPerSecond: ItemPropertyInfo
        LifestealTickRate: ItemPropertyInfo
        Lifetime: ItemPropertyInfo
        LiftChainCount: ItemPropertyInfo
        LiftChainRadius: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LiftHorizontal: ItemPropertyInfo
        LiftInitialDelay: ItemPropertyInfo
        LiftInitialRisingSpeed: ItemPropertyInfo
        LiftInitialVelocityEnd: ItemPropertyInfo
        LiftInitialVelocityStart: ItemPropertyInfo
        LiftTime: ItemPropertyInfo
        LightMeleeForce: ItemPropertyInfo
        LightningStrikeDamage: ItemPropertyInfo
        LightningStrikeDelay: ItemPropertyInfo
        LightningStrikeKnockBackForce: ItemPropertyInfo
        LightningStrikeRadius: ItemPropertyInfo
        LightningStrikes: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LockonConeAngle: ItemPropertyInfo
        LookDotMin: ItemPropertyInfo
        LookRadiusScale: ItemPropertyInfo
        LosingLockGraceTime: ItemPropertyInfo
        LowHealthEnemyDamageBonus: ItemPropertyInfo
        LowHealthEnemyThresholdPct: ItemPropertyInfo
        LowHealthHealingScalePercent: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MageTime: ItemPropertyInfo
        MagicDamagePerBullet: ItemPropertyInfo
        MakeInvisible: ItemPropertyInfo
        MarkDuration: ItemPropertyInfo
        MaxBonusBulletDamage: ItemPropertyInfo
        MaxBounces: ItemPropertyInfo
        MaxCameraAngleForSeeing: ItemPropertyInfo
        MaxChargeDuration: ItemPropertyInfo
        MaxChargeTime: ItemPropertyInfo
        MaxCooldownReductionsFromHits: ItemPropertyInfo
        MaxDaggers: ItemPropertyInfo
        MaxDamage: ItemPropertyInfo
        MaxDamageTime: ItemPropertyInfo
        MaxDeltaMovementControl: ItemPropertyInfo
        MaxDPS: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxFireRateSlowPercent: ItemPropertyInfo
        MaxFlyHeight: ItemPropertyInfo
        MaxGroundDashReduction: ItemPropertyInfo
        MaxGroundDashReductionPercent: ItemPropertyInfo
        MaxHealthHealOnCast: ItemPropertyInfo
        MaxHealthRegen: ItemPropertyInfo
        MaxHealthRegenPct: ItemPropertyInfo
        MaxHeatPower: ItemPropertyInfo
        MaxHPDPS: ItemPropertyInfo
        MaxLifetime: ItemPropertyInfo
        MaxLockonStacks: ItemPropertyInfo
        MaxMountDistance2D: ItemPropertyInfo
        MaxMoveSpeed: ItemPropertyInfo
        MaxPitch: ItemPropertyInfo
        MaxPlaneDistance: ItemPropertyInfo
        MaxPushVelocity: ItemPropertyInfo
        MaxRange: ItemPropertyInfo
        MaxRecasts: ItemPropertyInfo
        MaxRicochet: ItemPropertyInfo
        MaxSlow: ItemPropertyInfo
        MaxSlowDuration: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxSlowTime: ItemPropertyInfo
        MaxSoundDistance: ItemPropertyInfo
        MaxSpread: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MaxWallToWallDistance: ItemPropertyInfo
        MediumChargeDamagePct: ItemPropertyInfo
        MeleeAttackLength: ItemPropertyInfo
        MeleeAttackSpeedBonus: ItemPropertyInfo
        MeleeBurnDPS: ItemPropertyInfo
        MeleeDamageTakenScale: ItemPropertyInfo
        MeleeEMP: ItemPropertyInfo
        MeleeHalfAngle: ItemPropertyInfo
        MeleeHitCount: ItemPropertyInfo
        MeleeIgniteTime: ItemPropertyInfo
        MeleeRadius: ItemPropertyInfo
        MeleeSpeedBonusPercentage: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinAirTimeForStomp: ItemPropertyInfo
        MinBonusBulletDamage: ItemPropertyInfo
        MinChargeDamagePercent: ItemPropertyInfo
        MinDamage: ItemPropertyInfo
        MinDiffToCast: ItemPropertyInfo
        MinDistance: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        MinHealthTakenPct: ItemPropertyInfo
        MinHeight: ItemPropertyInfo
        MinimumSleepTime: ItemPropertyInfo
        MinRange: ItemPropertyInfo
        MinReflectionDOTResult: ItemPropertyInfo
        MinReflectionZ: ItemPropertyInfo
        MinShockDuration: ItemPropertyInfo
        MinSlowAmount: ItemPropertyInfo
        MinSlowDuration: ItemPropertyInfo
        MinSlowPercent: ItemPropertyInfo
        MinSpeed: ItemPropertyInfo
        MinSwapTime: ItemPropertyInfo
        MinTimeBeforeDestroy: ItemPropertyInfo
        MinTimeToTarget: ItemPropertyInfo
        MinVelocityZ: ItemPropertyInfo
        MinWallToWallDistance: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        ModifierRadius: ItemPropertyInfo
        MovementSlow: ItemPropertyInfo
        MovementSlowDuration: ItemPropertyInfo
        MovementSlowPct: ItemPropertyInfo
        MovementSpeedBonus: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MovementSpeedWhileShoot: ItemPropertyInfo
        MovementSpeedWhileZoom: ItemPropertyInfo
        MoveSlowDuration: ItemPropertyInfo
        MoveSlowPercent: ItemPropertyInfo
        MoveSpeed: ItemPropertyInfo
        MoveSpeedBonus: ItemPropertyInfo
        MoveSpeedBonusPct: ItemPropertyInfo
        MoveSpeedBonusPercentEnd: ItemPropertyInfo
        MoveSpeedBonusPercentStart: ItemPropertyInfo
        MoveSpeedGroundSlow: ItemPropertyInfo
        MoveSpeedLimit: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveSpeedMod: ItemPropertyInfo
        MoveSpeedPenaltyDuration: ItemPropertyInfo
        MoveSpeedPenaltyMaxSpeed: ItemPropertyInfo
        MoveSpeedPenaltyPerStack: ItemPropertyInfo
        MoveSpeedReduction: ItemPropertyInfo
        MoveSpeedSlowPct: ItemPropertyInfo
        MoveSpeedSlowPercent: ItemPropertyInfo
        MoveSpeedToTarget: ItemPropertyInfo
        MoveSpeedWhileShootingPenaltyReduction: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        MultiChain: ItemPropertyInfo
        MultiHitPenaltyPercentage: ItemPropertyInfo
        NoChannel: ItemPropertyInfo
        NoClipDuration: ItemPropertyInfo
        NonHeroDamagePercentOutgoing: ItemPropertyInfo
        NonHeroHealingFactor: ItemPropertyInfo
        NonHeroStack: ItemPropertyInfo
        NonLatchedDurationPct: ItemPropertyInfo
        NonPlayerCardResourceScale: ItemPropertyInfo
        NonPlayerRageScale: ItemPropertyInfo
        NormalDPS: ItemPropertyInfo
        NotInConeLosesLock: ItemPropertyInfo
        NotSeenByEnemiesRegen: ItemPropertyInfo
        NumBloodShards: ItemPropertyInfo
        NumWallSegments: ItemPropertyInfo
        OnLandDamageRadius: ItemPropertyInfo
        OnLandDamageRadiusStart: ItemPropertyInfo
        OpenHeight: ItemPropertyInfo
        OuterDamage: ItemPropertyInfo
        OutgoingDamage: ItemPropertyInfo
        OutgoingDamagePercent: ItemPropertyInfo
        OutgoingDamagePercentHungry: ItemPropertyInfo
        OutgoingProjectileLifetime: ItemPropertyInfo
        OutgoingTechDamagePercent: ItemPropertyInfo
        OverheatWarning: ItemPropertyInfo
        OverrideBulletRadius: ItemPropertyInfo
        ParriedStunTime: ItemPropertyInfo
        ParryMoveSpeed: ItemPropertyInfo
        ParticleRadiusMultiplier: ItemPropertyInfo
        PathLength: ItemPropertyInfo
        PathWidth: ItemPropertyInfo
        PauseOnTargetTime: ItemPropertyInfo
        PeakFireRateBonus: ItemPropertyInfo
        PercentHealthHealing: ItemPropertyInfo
        PetrifyDamage: ItemPropertyInfo
        PetrifyDamageBreakThreshold: ItemPropertyInfo
        PetrifyDuration: ItemPropertyInfo
        PhaseOutDuration: ItemPropertyInfo
        PlaceDistance: ItemPropertyInfo
        PlaneSpread: ItemPropertyInfo
        PlayerSpeedCheckScale: ItemPropertyInfo
        PopupForce: ItemPropertyInfo
        PopUpSpeed: ItemPropertyInfo
        PostCastHoldTime: ItemPropertyInfo
        PostCubeBuff: ItemPropertyInfo
        PostCubeBuffDuration: ItemPropertyInfo
        PostDashMaintainedVelocityRatio: ItemPropertyInfo
        PostInvisBuffDuration: ItemPropertyInfo
        PowerUpStages: ItemPropertyInfo
        PreDetonateDuration: ItemPropertyInfo
        PrepareTime: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        ProcDamage: ItemPropertyInfo
        ProcDamageBase: ItemPropertyInfo
        ProcDamagePercentage: ItemPropertyInfo
        ProcDamageStackCount: ItemPropertyInfo
        ProcMaxRange: ItemPropertyInfo
        ProjectileAmount: ItemPropertyInfo
        ProjectileArrivalTime: ItemPropertyInfo
        ProjectileFlyOutTime: ItemPropertyInfo
        ProjectileFlyReturnTime: ItemPropertyInfo
        ProjectileForwardSpeed: ItemPropertyInfo
        ProjectileHorizontalMinOffset: ItemPropertyInfo
        ProjectileIgnoreCollisionTime: ItemPropertyInfo
        ProjectileLifetime: ItemPropertyInfo
        ProjectileOffset: ItemPropertyInfo
        ProjectileOriginHeightOffset: ItemPropertyInfo
        ProjectileRedirectCount: ItemPropertyInfo
        ProjectileRowOffset: ItemPropertyInfo
        ProjectileSideFrequency: ItemPropertyInfo
        ProjectileSideSpeed: ItemPropertyInfo
        ProjectileThinkInterval: ItemPropertyInfo
        ProjectileTimeScale: ItemPropertyInfo
        PuddleDuration: ItemPropertyInfo
        PullSpeed: ItemPropertyInfo
        PullTargetSpeed: ItemPropertyInfo
        PulseDamage: ItemPropertyInfo
        PulseDPS: ItemPropertyInfo
        PulseInterval: ItemPropertyInfo
        PunchHalfHeight: ItemPropertyInfo
        PunchRollSlow: ItemPropertyInfo
        PunchRollSlowDuration: ItemPropertyInfo
        PurgeDebuffs: ItemPropertyInfo
        PurgeOnActivate: ItemPropertyInfo
        PurgeOnUse: ItemPropertyInfo
        PushAccel: ItemPropertyInfo
        PushBackDistance: ItemPropertyInfo
        PushBackForce: ItemPropertyInfo
        PushBackRadius: ItemPropertyInfo
        PushForce: ItemPropertyInfo
        PushNPCSpeed: ItemPropertyInfo
        PushSpeedMax: ItemPropertyInfo
        PushSpeedMid: ItemPropertyInfo
        PushSpeedMin: ItemPropertyInfo
        PushVelocity: ItemPropertyInfo
        Radius: ItemPropertyInfo
        RadiusGrowthTime: ItemPropertyInfo
        RadiusIncreasePerPulse: ItemPropertyInfo
        RadiusPerSecond: ItemPropertyInfo
        RageDrainDelayDuration: ItemPropertyInfo
        RageDrainRate: ItemPropertyInfo
        RagePerHeavyMelee: ItemPropertyInfo
        RagePerLightMelee: ItemPropertyInfo
        RagePerSpiritDamage: ItemPropertyInfo
        RagePerWeaponDamage: ItemPropertyInfo
        Range: ItemPropertyInfo
        RecastWindow: ItemPropertyInfo
        RecentDamageMarkDuration: ItemPropertyInfo
        RedirectVelocity: ItemPropertyInfo
        ReelSpeed: ItemPropertyInfo
        ReflectionSpeedFactor: ItemPropertyInfo
        RegenDamageInterval: ItemPropertyInfo
        RegenIncomingDamageDuration: ItemPropertyInfo
        RegenIncomingDamagePercent: ItemPropertyInfo
        ResetCooldownOnFriendlyHook: ItemPropertyInfo
        ResistancePerStack: ItemPropertyInfo
        ResourcePerCard: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RestoreHookCooldown: ItemPropertyInfo
        RestoreStaminaOnUse: ItemPropertyInfo
        RestrictionDuration: ItemPropertyInfo
        ReturnDamage: ItemPropertyInfo
        ReturnOffSetTargetDistance: ItemPropertyInfo
        ReturnRadius: ItemPropertyInfo
        ReturnUpVelocity: ItemPropertyInfo
        ReturnVelocity: ItemPropertyInfo
        RevealDuration: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        ReverseLifeLeech: ItemPropertyInfo
        ReverseLifeLeechDuration: ItemPropertyInfo
        RicochetAssistRatio: ItemPropertyInfo
        RicochetChance: ItemPropertyInfo
        RicochetCount: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        SalvageBonus_FireRate: ItemPropertyInfo
        SalvageBonus_Health: ItemPropertyInfo
        SalvageDuration: ItemPropertyInfo
        Scale: ItemPropertyInfo
        ScrapDamage: ItemPropertyInfo
        SearchAngle: ItemPropertyInfo
        SearchRadius: ItemPropertyInfo
        SearchRate: ItemPropertyInfo
        SecondaryHealHeroRange: ItemPropertyInfo
        SecondDoorPlacementWindow: ItemPropertyInfo
        SecondHit: ItemPropertyInfo
        SecondHitDamagePercentage: ItemPropertyInfo
        SegmentEmitTime: ItemPropertyInfo
        SelfBuffDuration: ItemPropertyInfo
        SelfBumpImpulse: ItemPropertyInfo
        SelfDamage: ItemPropertyInfo
        SelfDamagePct: ItemPropertyInfo
        SelfDamagePercent: ItemPropertyInfo
        SelfDPS: ItemPropertyInfo
        SelfLaunchPercent: ItemPropertyInfo
        SelfShoveForce: ItemPropertyInfo
        SenseRange: ItemPropertyInfo
        ShadowFormDurationOnKill: ItemPropertyInfo
        ShareDamagePercent: ItemPropertyInfo
        ShareDamageThreshold: ItemPropertyInfo
        ShareWithFriendsRadius: ItemPropertyInfo
        ShieldDuration: ItemPropertyInfo
        ShockDelay: ItemPropertyInfo
        ShockRadius: ItemPropertyInfo
        ShootDelay: ItemPropertyInfo
        ShootDuration: ItemPropertyInfo
        ShootInterval: ItemPropertyInfo
        ShortChargeDamagePct: ItemPropertyInfo
        ShortCooldown: ItemPropertyInfo
        ShotCount: ItemPropertyInfo
        ShotRadius: ItemPropertyInfo
        ShotsToProc: ItemPropertyInfo
        ShouldBounce: ItemPropertyInfo
        SideMoveSpeedReduction: ItemPropertyInfo
        Silence: ItemPropertyInfo
        SilenceBombSpeed: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SilenceOnDrain: ItemPropertyInfo
        SilenceOnHeavyDuration: ItemPropertyInfo
        SilenceRadius: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlamSpeed: ItemPropertyInfo
        SlashCollisionRadius: ItemPropertyInfo
        SlashForwardOffset: ItemPropertyInfo
        SlashHeight: ItemPropertyInfo
        SlashLength: ItemPropertyInfo
        SlashRadius: ItemPropertyInfo
        SlashRange: ItemPropertyInfo
        SleepDuration: ItemPropertyInfo
        SleepMoveSpeed: ItemPropertyInfo
        SleepWakeUpDelay: ItemPropertyInfo
        SlideForce: ItemPropertyInfo
        SlideLeapSpeedPenaltyMax: ItemPropertyInfo
        SlideLeapSpeedPenaltyTime: ItemPropertyInfo
        SlideResist: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowDurationPerStack: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistance: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SlowTargetDuration: ItemPropertyInfo
        SmokeDuration: ItemPropertyInfo
        SpawnDuration: ItemPropertyInfo
        Speed: ItemPropertyInfo
        SpeedBoostDuration: ItemPropertyInfo
        SpeedBurstDuration: ItemPropertyInfo
        SpeedBurstSpeed: ItemPropertyInfo
        SpeedChange: ItemPropertyInfo
        SpeedInitial: ItemPropertyInfo
        SpeedLostDuration: ItemPropertyInfo
        SpeedOnLand: ItemPropertyInfo
        SpeedOnLandDuration: ItemPropertyInfo
        SpellLifesteal: ItemPropertyInfo
        SpherePushExtraDistance: ItemPropertyInfo
        SphereRadius: ItemPropertyInfo
        SpiderArmingTime: ItemPropertyInfo
        SpiderChaseVelocity: ItemPropertyInfo
        SpiderClimbHeight: ItemPropertyInfo
        SpiderCount: ItemPropertyInfo
        SpiderDamage: ItemPropertyInfo
        SpiderDistAboveGround: ItemPropertyInfo
        SpiderExplodeRadius: ItemPropertyInfo
        SpiderFloatDownRate: ItemPropertyInfo
        SpiderGravity: ItemPropertyInfo
        SpiderLifetime: ItemPropertyInfo
        SpiderRandomPositionRadius: ItemPropertyInfo
        SpiderSearchRadius: ItemPropertyInfo
        SpiderTickRate: ItemPropertyInfo
        SpinDuration: ItemPropertyInfo
        SpinSlowDuration: ItemPropertyInfo
        SpinSlowPercent: ItemPropertyInfo
        SpiritReducedPerStack: ItemPropertyInfo
        SpiritResReducedPerStack: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SplitAngle: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngle: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDistance: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        SpreadRadius: ItemPropertyInfo
        SpreadTargets: ItemPropertyInfo
        SprintSpeedBonus: ItemPropertyInfo
        StackDuration: ItemPropertyInfo
        StacksCanDecay: ItemPropertyInfo
        StageDuration: ItemPropertyInfo
        StageRadius: ItemPropertyInfo
        StakeCount: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownIncrease: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StaminaHeal: ItemPropertyInfo
        StaminaHungry: ItemPropertyInfo
        StaminaRecoveryDisabledDuration: ItemPropertyInfo
        StaminaRecoveryReduction: ItemPropertyInfo
        StaminaReduction: ItemPropertyInfo
        StandStillMinTime: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StatStealDamageInstances: ItemPropertyInfo
        StatStealDuration: ItemPropertyInfo
        StatueArmTime: ItemPropertyInfo
        StatueHealth: ItemPropertyInfo
        StatueScale: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StompBounceHeight: ItemPropertyInfo
        StompDamage: ItemPropertyInfo
        StompDamagePerMeterPrimary: ItemPropertyInfo
        StompDamagePerMeterSecondary: ItemPropertyInfo
        StompDamagePrimaryRange: ItemPropertyInfo
        StompRange: ItemPropertyInfo
        StompStunDuration: ItemPropertyInfo
        StompVerticalThreshold: ItemPropertyInfo
        StompWidth: ItemPropertyInfo
        StrikeVelocity: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        StunOnLand: ItemPropertyInfo
        StunsTargets: ItemPropertyInfo
        StunTargetOnExplode: ItemPropertyInfo
        SummonCasterHealthPct: ItemPropertyInfo
        SummonCount: ItemPropertyInfo
        SummonDPS: ItemPropertyInfo
        SummonHealth: ItemPropertyInfo
        SummonLifetime: ItemPropertyInfo
        SummonMoveSpeed: ItemPropertyInfo
        SwapEndDelay: ItemPropertyInfo
        SwapTime: ItemPropertyInfo
        SwapTotalDamage: ItemPropertyInfo
        SweepSpeed: ItemPropertyInfo
        SwingLineBulletDistance: ItemPropertyInfo
        TackleRadius: ItemPropertyInfo
        TackleSpeed: ItemPropertyInfo
        TargetBounceCount: ItemPropertyInfo
        TargetBounceRange: ItemPropertyInfo
        TargetBulletEvasionChance: ItemPropertyInfo
        TargetingConeAngle: ItemPropertyInfo
        TargetingDuration: ItemPropertyInfo
        TargetingWidth: ItemPropertyInfo
        TargetLifesteal: ItemPropertyInfo
        TargetLifestealNonHero: ItemPropertyInfo
        TargetLingerDuration: ItemPropertyInfo
        TargetOffSetScale: ItemPropertyInfo
        TargetPracticeDuration: ItemPropertyInfo
        TargetsPerTick: ItemPropertyInfo
        TechAmpLinger: ItemPropertyInfo
        TechAmpPerBullet: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechCleaveExpireTime: ItemPropertyInfo
        TechLifestealPercent: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechPowerAmpBonus: ItemPropertyInfo
        TechPowerAmpBonusDuration: ItemPropertyInfo
        TechPowerAmpBonusMaxStacks: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TechResistDebuff: ItemPropertyInfo
        TechShield: ItemPropertyInfo
        TechShieldDuration: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherLength: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        TetherSharedHealPct: ItemPropertyInfo
        ThinkInterval: ItemPropertyInfo
        ThirdHitDamagePercentage: ItemPropertyInfo
        ThrowDamage: ItemPropertyInfo
        ThrowDistance: ItemPropertyInfo
        ThrownObjectRadius: ItemPropertyInfo
        ThrowSpeed: ItemPropertyInfo
        ThrowStraightDuration: ItemPropertyInfo
        TickInterval: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TickTime: ItemPropertyInfo
        TimeBeforeCursed: ItemPropertyInfo
        TimeBeforeProjectileLaunch: ItemPropertyInfo
        TimeBetweenGrenades: ItemPropertyInfo
        TimeBetweenSegments: ItemPropertyInfo
        TimeBetweenShots: ItemPropertyInfo
        TimeScaleDebuff: ItemPropertyInfo
        TimeScaleDuration: ItemPropertyInfo
        TimeToFullCharge: ItemPropertyInfo
        TimeToGainLockonStack: ItemPropertyInfo
        TimeToLoseLockonStack: ItemPropertyInfo
        TimeToMaxDistance: ItemPropertyInfo
        TimeUntilStasis: ItemPropertyInfo
        TimeWallDepth: ItemPropertyInfo
        TimeWallDepthVisualScale: ItemPropertyInfo
        TimeWallFormationTime: ItemPropertyInfo
        TimeWallHeight: ItemPropertyInfo
        TimeWallTimeScale: ItemPropertyInfo
        TimeWallWidth: ItemPropertyInfo
        TimeWarpRadius: ItemPropertyInfo
        ToggleOffDelay: ItemPropertyInfo
        TornadoSpeed: ItemPropertyInfo
        TossAngle: ItemPropertyInfo
        TossBackSpeed: ItemPropertyInfo
        TossGroundSideRatio: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TossSpeedUpWall: ItemPropertyInfo
        TossSpeedWall: ItemPropertyInfo
        TossUpMagnitude: ItemPropertyInfo
        TossUpSpeed: ItemPropertyInfo
        TossVelocity: ItemPropertyInfo
        TotalBolts: ItemPropertyInfo
        TotalShotCount: ItemPropertyInfo
        TotalShots: ItemPropertyInfo
        TotalSwaps: ItemPropertyInfo
        TotalTetherTargets: ItemPropertyInfo
        TrackingDistance: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TrackingTime: ItemPropertyInfo
        TrackingVariance: ItemPropertyInfo
        TrackSpeedFar: ItemPropertyInfo
        TrackSpeedNear: ItemPropertyInfo
        TrailingTeamBonusSprintSpeed: ItemPropertyInfo
        TrailInterval: ItemPropertyInfo
        TrapHeight: ItemPropertyInfo
        TripGravity: ItemPropertyInfo
        TripTime: ItemPropertyInfo
        TripUpSpeed: ItemPropertyInfo
        TurnRateMax: ItemPropertyInfo
        TurnRateSlowDuration: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackFalloffEnd: ItemPropertyInfo
        TurretAttackFalloffStart: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretBaseHealth: ItemPropertyInfo
        TurretBulletTargetAngle: ItemPropertyInfo
        TurretBulletTargetRadius: ItemPropertyInfo
        TurretBulletVerticalOffset: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretDPS: ItemPropertyInfo
        TurretHealMult: ItemPropertyInfo
        TurretHealthPerBoon: ItemPropertyInfo
        TurretHealthScaling: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        UnstoppableCastDelay: ItemPropertyInfo
        UpBoostSpeed: ItemPropertyInfo
        UpFactor: ItemPropertyInfo
        UpForce: ItemPropertyInfo
        UpImpulse: ItemPropertyInfo
        UppercutBuffOnHit: ItemPropertyInfo
        UppercutDamage: ItemPropertyInfo
        UseHeavyMelee: ItemPropertyInfo
        VacuumRadius: ItemPropertyInfo
        VenomBuildupPerShot: ItemPropertyInfo
        VenomDuration: ItemPropertyInfo
        VenomMaxDamage: ItemPropertyInfo
        VenomMaxDamageHealthPercentage: ItemPropertyInfo
        VenomMinDamage: ItemPropertyInfo
        VenomMinDamageHealthPercentage: ItemPropertyInfo
        VenomMissingHealthDamagePercentage: ItemPropertyInfo
        VentEfficiency: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        VerticalSpeed: ItemPropertyInfo
        VictimDamageReduction: ItemPropertyInfo
        VictimDamageTakenScale: ItemPropertyInfo
        VictimPushTime: ItemPropertyInfo
        VictimStackDuration: ItemPropertyInfo
        ViewPunch: ItemPropertyInfo
        VisibilityTime: ItemPropertyInfo
        VisualSplashRadius: ItemPropertyInfo
        VolleyInterval: ItemPropertyInfo
        VulnerabilityPerStack: ItemPropertyInfo
        WallImpactLookAheadDistance: ItemPropertyInfo
        WallImpactRange: ItemPropertyInfo
        WallLatchIdealDist: ItemPropertyInfo
        WallLatchSettleDist: ItemPropertyInfo
        WallLatchSettleTime: ItemPropertyInfo
        WallStunDuration: ItemPropertyInfo
        WeaponDamageBonus: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponDamageBonusPerSec: ItemPropertyInfo
        WeaponDamagePerHeat: ItemPropertyInfo
        WeaponDamageScale: ItemPropertyInfo
        WeaponFireRateBonus: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
        WeaponPowerBuffDuration: ItemPropertyInfo
        WeaponPowerDebuff: ItemPropertyInfo
        WeaponPowerIncreaseDuration: ItemPropertyInfo
        WeaponReadyDuration: ItemPropertyInfo
        WeaponRecoilReduction: ItemPropertyInfo
        WeaponSpreadPenalty: ItemPropertyInfo
        WebArmTime: ItemPropertyInfo
        WebDuration: ItemPropertyInfo
        WebWallTickRate: ItemPropertyInfo
        WhirlwindDuration: ItemPropertyInfo
        WhirlwindEvasionChance: ItemPropertyInfo
        WreckingBallDamage: ItemPropertyInfo
        WreckingBallPushForce: ItemPropertyInfo
        ZipAcc: ItemPropertyInfo
        ZiplineProtectionDamageAmp: ItemPropertyInfo
        ZiplineProtectionSlowDurationOnHit: ItemPropertyInfo
        ZipSpeedInner: ItemPropertyInfo
        ZipSpeedOuter: ItemPropertyInfo
        ZoomBias: ItemPropertyInfo
        ZoomTime: ItemPropertyInfo
    }

    type UpgradeItem implements Item {
        activation: String
        class_name: String!
        cost: Int
        description: ItemDescription
        disabled: Boolean
        hero: Hero
        heroes: [Hero]
        id: ID!
        image_webp: String
        image: String
        is_active_item: Boolean
        item_slot_type: String
        item_tier: Int
        name: String
        properties: UpgradeItemProperties
        shop_image_small_webp: String
        shop_image_small: String
        shop_image_webp: String
        shop_image: String
        shopable: Boolean
        start_trained: Boolean
        tooltip_sections: [TooltipSection]
        type: String
        update_time: Int
        weapon_info: UpgradeItemWeaponInfo
    }

    type UpgradeItemWeaponInfo implements ItemWeaponInfo {
        bullet_speed_curve: BulletSpeedCurve
    }

    type UpgradeItemProperties implements ItemProperties {
        AbilityCastDelay: ItemPropertyInfo
        AbilityCastRange: ItemPropertyInfo
        AbilityChannelTime: ItemPropertyInfo
        AbilityCharges: ItemPropertyInfo
        AbilityChargeUpTime: ItemPropertyInfo
        AbilityCooldown: ItemPropertyInfo
        AbilityCooldownBetweenCharge: ItemPropertyInfo
        AbilityDuration: ItemPropertyInfo
        AbilityLifestealPercentHero: ItemPropertyInfo
        AbilityLifestealPercentHeroPassive: ItemPropertyInfo
        AbilityPostCastDuration: ItemPropertyInfo
        AbilityResourceCost: ItemPropertyInfo
        AbilityUnitTargetLimit: ItemPropertyInfo
        ActivatedFireRate: ItemPropertyInfo
        ActivateTime: ItemPropertyInfo
        ActiveBonusFireRate: ItemPropertyInfo
        ActiveBonusLifesteal: ItemPropertyInfo
        ActiveBonusMoveSpeed: ItemPropertyInfo
        ActiveMoveSpeedPenalty: ItemPropertyInfo
        ActiveRadius: ItemPropertyInfo
        ActiveReloadPercent: ItemPropertyInfo
        AirControlPercent: ItemPropertyInfo
        AirJumps: ItemPropertyInfo
        AirJumpVerticalSpeedPercent: ItemPropertyInfo
        AirMoveIncreasePercent: ItemPropertyInfo
        AmbushBonusFireRate: ItemPropertyInfo
        AmbushBonusMeleeDamage: ItemPropertyInfo
        AmbushBonusTechPower: ItemPropertyInfo
        AmbushDuration: ItemPropertyInfo
        AmmoPerSoul: ItemPropertyInfo
        AmmoReloadPercent: ItemPropertyInfo
        ArmingTime: ItemPropertyInfo
        ArmorLossPerHit: ItemPropertyInfo
        AssaultDuration: ItemPropertyInfo
        AssaultFireRate: ItemPropertyInfo
        AssaultLifestealPercent: ItemPropertyInfo
        AttackConeAngle: ItemPropertyInfo
        AuraRadius: ItemPropertyInfo
        BackwardsShotDelayTime: ItemPropertyInfo
        BarrierDuration: ItemPropertyInfo
        BaseAttackDamagePercent: ItemPropertyInfo
        BaseAttackDamagePercentAtMaxDuration: ItemPropertyInfo
        BaseAttackDamagePercentBonus: ItemPropertyInfo
        BaseBonusCounter: ItemPropertyInfo
        BaseBonusWeaponPower: ItemPropertyInfo
        BaseDamagePct: ItemPropertyInfo
        BaseDamagePerShot: ItemPropertyInfo
        BonusAbilityCharges: ItemPropertyInfo
        BonusAbilityDurationPercent: ItemPropertyInfo
        BonusAttackRangePercent: ItemPropertyInfo
        BonusBulletSpeedPercent: ItemPropertyInfo
        BonusChargedAbilityDamage: ItemPropertyInfo
        BonusChargedCooldownReduction: ItemPropertyInfo
        BonusClipPerKill: ItemPropertyInfo
        BonusClipSize: ItemPropertyInfo
        BonusClipSizePercent: ItemPropertyInfo
        BonusDamagePerHero: ItemPropertyInfo
        BonusFireRate: ItemPropertyInfo
        BonusFireRateNPC: ItemPropertyInfo
        BonusHeadshotDamage: ItemPropertyInfo
        BonusHealth: ItemPropertyInfo
        BonusHealthRegen: ItemPropertyInfo
        BonusHeavyMeleeDamage: ItemPropertyInfo
        BonusMeleeDamagePercent: ItemPropertyInfo
        BonusMovespeed: ItemPropertyInfo
        BonusMoveSpeed: ItemPropertyInfo
        BonusPerChain: ItemPropertyInfo
        BonusReloadSpeed: ItemPropertyInfo
        BonusReloadTime: ItemPropertyInfo
        BonusShotsDuration: ItemPropertyInfo
        BonusSoulsPct: ItemPropertyInfo
        BonusSpirit: ItemPropertyInfo
        BonusSpiritForChargedAbilities: ItemPropertyInfo
        BonusSpiritMaxTime: ItemPropertyInfo
        BonusSpiritMin: ItemPropertyInfo
        BonusSpiritWindow: ItemPropertyInfo
        BonusSprintSpeed: ItemPropertyInfo
        BonusWeaponPower: ItemPropertyInfo
        BonusZoomPercent: ItemPropertyInfo
        BuffBulletResist: ItemPropertyInfo
        BuffDamageMult: ItemPropertyInfo
        BuffDuration: ItemPropertyInfo
        BuffMeleeDamageBoost: ItemPropertyInfo
        BuffMoveSpeedBonus: ItemPropertyInfo
        BuffTechResist: ItemPropertyInfo
        BuildUpDuration: ItemPropertyInfo
        BuildUpPerShot: ItemPropertyInfo
        BulletArmor: ItemPropertyInfo
        BulletArmorReduction: ItemPropertyInfo
        BulletDamageReflectedPct: ItemPropertyInfo
        BulletLifestealPercent: ItemPropertyInfo
        BulletProcDeflectionPercent: ItemPropertyInfo
        BulletResist: ItemPropertyInfo
        BulletResistBelowThreshold: ItemPropertyInfo
        BulletResistDuration: ItemPropertyInfo
        BulletResistPerStack: ItemPropertyInfo
        BulletResistReduction: ItemPropertyInfo
        BulletsBonusMagicDamage: ItemPropertyInfo
        BulletShieldDamagePercent: ItemPropertyInfo
        BulletShieldMaxHealth: ItemPropertyInfo
        BulletSpeedOverride: ItemPropertyInfo
        BulletSplitShot: ItemPropertyInfo
        BurstFireShotPercent: ItemPropertyInfo
        BurstFireShotsFromClipPercent: ItemPropertyInfo
        CaptureRadius: ItemPropertyInfo
        CasterBuffDuration: ItemPropertyInfo
        CasterHealthPercent: ItemPropertyInfo
        ChainCount: ItemPropertyInfo
        ChainRadius: ItemPropertyInfo
        ChainTickRate: ItemPropertyInfo
        ChannelMoveSpeed: ItemPropertyInfo
        CloseRangeBonusDamageRange: ItemPropertyInfo
        CloseRangeBonusWeaponPower: ItemPropertyInfo
        CombatBarrier: ItemPropertyInfo
        CooldownBetweenChargeReduction: ItemPropertyInfo
        CooldownOnMiss: ItemPropertyInfo
        CooldownReduction: ItemPropertyInfo
        CooldownReductionFlat: ItemPropertyInfo
        CooldownReductionOnChargedAbilities: ItemPropertyInfo
        CooldownReductionPctOnNonHeroes: ItemPropertyInfo
        CooldownReductionPctOnOthers: ItemPropertyInfo
        CooldownReductionPerHit: ItemPropertyInfo
        CritDamagePercent: ItemPropertyInfo
        CycleTimeFireRateDecrease: ItemPropertyInfo
        Damage: ItemPropertyInfo
        DamageDuration: ItemPropertyInfo
        DamageHeight: ItemPropertyInfo
        DamagePctVsNonHeroes: ItemPropertyInfo
        DamagePerChain: ItemPropertyInfo
        DamagePulseAmount: ItemPropertyInfo
        DamagePulseRadius: ItemPropertyInfo
        DamageReduction: ItemPropertyInfo
        DamageThreshold: ItemPropertyInfo
        DamageThresholdDuration: ItemPropertyInfo
        DamageToStack: ItemPropertyInfo
        DamageWindow: ItemPropertyInfo
        DampingFactor: ItemPropertyInfo
        DeathImmunityDamageReduction: ItemPropertyInfo
        DeathImmunityDuration: ItemPropertyInfo
        DebuffDuration: ItemPropertyInfo
        DebuffRadius: ItemPropertyInfo
        DeflectionPercent: ItemPropertyInfo
        DeflectionRandomness: ItemPropertyInfo
        DegenResistance: ItemPropertyInfo
        DelayBeforeStun: ItemPropertyInfo
        DelayDuration: ItemPropertyInfo
        DiminishingMultiplier: ItemPropertyInfo
        DirectionVariance: ItemPropertyInfo
        DotDuration: ItemPropertyInfo
        DotHealthPercent: ItemPropertyInfo
        DotMultiplerTroopers: ItemPropertyInfo
        DPS: ItemPropertyInfo
        DPSIncrease: ItemPropertyInfo
        DPSMax: ItemPropertyInfo
        DropDownSpeed: ItemPropertyInfo
        EMPDuration: ItemPropertyInfo
        EMPProcChance: ItemPropertyInfo
        EndRadius: ItemPropertyInfo
        EnemyLifeThreshold: ItemPropertyInfo
        ExplodeDamage: ItemPropertyInfo
        ExplodeRadius: ItemPropertyInfo
        ExplosionDamage: ItemPropertyInfo
        ExplosionRadius: ItemPropertyInfo
        FervorFireRate: ItemPropertyInfo
        FervorMovespeed: ItemPropertyInfo
        FervorTechResist: ItemPropertyInfo
        FireRateBonus: ItemPropertyInfo
        FireRatePerKill: ItemPropertyInfo
        FireRateSlow: ItemPropertyInfo
        FireRateSlowDuration: ItemPropertyInfo
        FlyMoveSpeed: ItemPropertyInfo
        FreezeDuration: ItemPropertyInfo
        FullInvisDistance: ItemPropertyInfo
        GalvanicBuffDuration: ItemPropertyInfo
        GalvanicDebuffDuration: ItemPropertyInfo
        GroundDashReductionPercent: ItemPropertyInfo
        GrowthPerMeter: ItemPropertyInfo
        GuardianWardCombatBarrier: ItemPropertyInfo
        HeadShotBonusDamage: ItemPropertyInfo
        HeadshotBonusSteal: ItemPropertyInfo
        HealAmount: ItemPropertyInfo
        HealAmpCastPercent: ItemPropertyInfo
        HealAmpReceivePenaltyPercent: ItemPropertyInfo
        HealAmpRegenPenaltyPercent: ItemPropertyInfo
        HealAmpRegenPercent: ItemPropertyInfo
        HealFromHero: ItemPropertyInfo
        HealFromNPC: ItemPropertyInfo
        HealingPerCast: ItemPropertyInfo
        HealInterval: ItemPropertyInfo
        HealLifePercentOutOfCombat: ItemPropertyInfo
        HealOnActivate: ItemPropertyInfo
        HealOnKill: ItemPropertyInfo
        HealOnLevelHealAmount: ItemPropertyInfo
        HealOnSuccess: ItemPropertyInfo
        HealOnVeil: ItemPropertyInfo
        HealPercentAmount: ItemPropertyInfo
        HealPercentPerHeadshot: ItemPropertyInfo
        HealPerStack: ItemPropertyInfo
        HealRadius: ItemPropertyInfo
        HealthDamagePercent: ItemPropertyInfo
        HealthDrainedPerSecond: ItemPropertyInfo
        HealthSteal: ItemPropertyInfo
        HealthThreshold: ItemPropertyInfo
        HeavyMeleeMultiplier: ItemPropertyInfo
        HeightOffGround: ItemPropertyInfo
        HeroMultiplier: ItemPropertyInfo
        HeroTargetBonus: ItemPropertyInfo
        HighGroundBonusWeaponPower: ItemPropertyInfo
        ImbuedBonusDamage: ItemPropertyInfo
        ImbuedBonusDuration: ItemPropertyInfo
        ImbuedTechPower: ItemPropertyInfo
        ImmunityDuration: ItemPropertyInfo
        ImpactDamage: ItemPropertyInfo
        ImpactHeight: ItemPropertyInfo
        InitialFireRateDecrease: ItemPropertyInfo
        InitialWidth: ItemPropertyInfo
        InteruptCooldown: ItemPropertyInfo
        Interval: ItemPropertyInfo
        IntraBurstFireRateIncrease: ItemPropertyInfo
        InvisAlertWhenFading: ItemPropertyInfo
        InvisCancelOnDamage: ItemPropertyInfo
        InvisDuration: ItemPropertyInfo
        InvisFadeToDuration: ItemPropertyInfo
        InvisMoveSpeedMod: ItemPropertyInfo
        ItemCooldownReduction: ItemPropertyInfo
        JumpVelocityHidden: ItemPropertyInfo
        KillBonusMoveSpeedPerStack: ItemPropertyInfo
        KillWindow: ItemPropertyInfo
        LifestealHeal: ItemPropertyInfo
        LifestealHealPercent: ItemPropertyInfo
        LifestrikeHeal: ItemPropertyInfo
        LifestrikeHealPercent: ItemPropertyInfo
        LifeThreshold: ItemPropertyInfo
        LiftHeight: ItemPropertyInfo
        LightMeleeAmmo: ItemPropertyInfo
        LightMeleeCooldownMult: ItemPropertyInfo
        LightMeleeStacks: ItemPropertyInfo
        LightMeleeTimeWindow: ItemPropertyInfo
        LingerDuration: ItemPropertyInfo
        LocalBulletArmorReduction: ItemPropertyInfo
        LongRangeBonusWeaponPower: ItemPropertyInfo
        LongRangeBonusWeaponPowerMinRange: ItemPropertyInfo
        LowHealthLifeStealPercent: ItemPropertyInfo
        LowHealthPercentThreshold: ItemPropertyInfo
        LowHealthThreshold: ItemPropertyInfo
        MagicIncreasePerStack: ItemPropertyInfo
        MagicResistReduction: ItemPropertyInfo
        MaxArmorStacks: ItemPropertyInfo
        MaxBonusDuration: ItemPropertyInfo
        MaxBulletResist: ItemPropertyInfo
        MaxClipBonus: ItemPropertyInfo
        MaxFallSpeed: ItemPropertyInfo
        MaxFireRateIncrease: ItemPropertyInfo
        MaxHealthDamage: ItemPropertyInfo
        MaxHealthLossPercent: ItemPropertyInfo
        MaxHealthPercentAsDPS: ItemPropertyInfo
        MaxHeightForBonus: ItemPropertyInfo
        MaxKillBonusMoveSpeedStack: ItemPropertyInfo
        MaxLandingSpeed: ItemPropertyInfo
        MaxSlowPercent: ItemPropertyInfo
        MaxStacks: ItemPropertyInfo
        MaxWeaponPower: ItemPropertyInfo
        MeleeDistanceScale: ItemPropertyInfo
        MeleeResistPercent: ItemPropertyInfo
        MinAimAngle: ItemPropertyInfo
        MinEffectiveness: ItemPropertyInfo
        MinimumDamage: ItemPropertyInfo
        MinimumHealAmount: ItemPropertyInfo
        MinTargetsRequired: ItemPropertyInfo
        ModelScale: ItemPropertyInfo
        ModelScaleGrowth: ItemPropertyInfo
        MovementSpeedBonusDuration: ItemPropertyInfo
        MovementSpeedSlow: ItemPropertyInfo
        MovementThresholdSq: ItemPropertyInfo
        MoveSpeedMax: ItemPropertyInfo
        MoveWhileShootingSpeedPenaltyReductionPercent: ItemPropertyInfo
        MoveWhileZoomedSpeedPenaltyReductionPercent: ItemPropertyInfo
        NanoTechPerShot: ItemPropertyInfo
        NonBurstFireConversionFactor: ItemPropertyInfo
        NonHeroAbilityLifestealTooltipOnly: ItemPropertyInfo
        NonHeroHealPct: ItemPropertyInfo
        NonHeroMult: ItemPropertyInfo
        NonHeroReductionPercent: ItemPropertyInfo
        NonPlayerBonusWeaponPower: ItemPropertyInfo
        NonPlayerBulletResist: ItemPropertyInfo
        NormalizedClipEmptySpeedIncrease: ItemPropertyInfo
        NPCDamageMult: ItemPropertyInfo
        OutgoingDamagePenaltyPercent: ItemPropertyInfo
        OutOfCombatHealthRegen: ItemPropertyInfo
        OverdriveClipDuration: ItemPropertyInfo
        ParryCooldownReduction: ItemPropertyInfo
        ParrySuccessHealPercentage: ItemPropertyInfo
        ParticleRadius: ItemPropertyInfo
        PercentDamage: ItemPropertyInfo
        PerfectBurstWeaponPower: ItemPropertyInfo
        ProcAmmoConsumed: ItemPropertyInfo
        ProcBaseAttackDamagePercent: ItemPropertyInfo
        ProcBaseAttackDamagePercentAltFire: ItemPropertyInfo
        ProcBonusMagicDamage: ItemPropertyInfo
        ProcBulletVelocity: ItemPropertyInfo
        ProcChance: ItemPropertyInfo
        ProcCooldown: ItemPropertyInfo
        Radius: ItemPropertyInfo
        ReduceFootstepSound: ItemPropertyInfo
        RegenDuration: ItemPropertyInfo
        Regeneration: ItemPropertyInfo
        RegenerationDuration: ItemPropertyInfo
        RegenWhileInvisible: ItemPropertyInfo
        ReloadSpeedMultipler: ItemPropertyInfo
        ReProcLockoutTime: ItemPropertyInfo
        ResistReduction: ItemPropertyInfo
        ResistReductionDuration: ItemPropertyInfo
        RespawnBonusHealthDuration: ItemPropertyInfo
        RespawnDelay: ItemPropertyInfo
        RespawnHealthPercent: ItemPropertyInfo
        RestoreDelay: ItemPropertyInfo
        ReturnFireBulletResist: ItemPropertyInfo
        RevealOnDamageDuration: ItemPropertyInfo
        RevealOnSpottedDuration: ItemPropertyInfo
        RicochetDamagePercent: ItemPropertyInfo
        RicochetRadius: ItemPropertyInfo
        RicochetTargetsTooltipOnly: ItemPropertyInfo
        SelfModifier: ItemPropertyInfo
        ShootDurationForMax: ItemPropertyInfo
        SilenceDuration: ItemPropertyInfo
        SingleTargetPlayerMultiplier: ItemPropertyInfo
        SkipFrames: ItemPropertyInfo
        SlamDownRadius: ItemPropertyInfo
        SlamdownSpeed: ItemPropertyInfo
        SlideScale: ItemPropertyInfo
        SlowDuration: ItemPropertyInfo
        SlowPercent: ItemPropertyInfo
        SlowResistancePercent: ItemPropertyInfo
        SpawnTimePenalty: ItemPropertyInfo
        SpecialShotsBonusFireRate: ItemPropertyInfo
        SpellAmplificationMultiplier: ItemPropertyInfo
        SpellParryDuration: ItemPropertyInfo
        SpellShieldFlavorText: ItemPropertyInfo
        SpellShieldLingerDuration: ItemPropertyInfo
        SpinUpDecay: ItemPropertyInfo
        SpinUpTime: ItemPropertyInfo
        SpiritDamage: ItemPropertyInfo
        SpiritDamageReductionProc: ItemPropertyInfo
        SpiritDamageReflectedPct: ItemPropertyInfo
        SpiritPower: ItemPropertyInfo
        SpiritPowerInnate: ItemPropertyInfo
        SpiritPowerPerSoul: ItemPropertyInfo
        SpiritSteal: ItemPropertyInfo
        SpiritStealDuration: ItemPropertyInfo
        SpiritStolePerHit: ItemPropertyInfo
        SpottedRadius: ItemPropertyInfo
        SpreadAngleDegrees: ItemPropertyInfo
        SpreadDuration: ItemPropertyInfo
        StackingBonusHealth: ItemPropertyInfo
        StackingBonusSprintSpeed: ItemPropertyInfo
        StackingGoldPerMinute: ItemPropertyInfo
        StackingTechRadiusMultiplier: ItemPropertyInfo
        StackingTechRangeMultiplier: ItemPropertyInfo
        StackLossFrequency: ItemPropertyInfo
        StackLostPerDeath: ItemPropertyInfo
        Stamina: ItemPropertyInfo
        StaminaCooldownReduction: ItemPropertyInfo
        StaminaToRestore: ItemPropertyInfo
        StartRadius: ItemPropertyInfo
        StasisRadius: ItemPropertyInfo
        StationaryRecoilReduction: ItemPropertyInfo
        StationaryWeaponPower: ItemPropertyInfo
        StatusResistancePercent: ItemPropertyInfo
        StealDuration: ItemPropertyInfo
        StealPerHit: ItemPropertyInfo
        StealPerKill: ItemPropertyInfo
        StoredSpiritDamage: ItemPropertyInfo
        StunDelay: ItemPropertyInfo
        StunDuration: ItemPropertyInfo
        SummonDuration: ItemPropertyInfo
        TechArmor: ItemPropertyInfo
        TechArmorDamageReduction: ItemPropertyInfo
        TechArmorGain: ItemPropertyInfo
        TechCleaveDamagePercent: ItemPropertyInfo
        TechCleaveRadius: ItemPropertyInfo
        TechDamagePercent: ItemPropertyInfo
        TechDamageReduction: ItemPropertyInfo
        TechPower: ItemPropertyInfo
        TechPowerGain: ItemPropertyInfo
        TechPowerPercent: ItemPropertyInfo
        TechPowerReduction: ItemPropertyInfo
        TechRadiusMultiplier: ItemPropertyInfo
        TechRadiusMultiplierBuff: ItemPropertyInfo
        TechRangeMultiplier: ItemPropertyInfo
        TechRangeMultiplierBuff: ItemPropertyInfo
        TechResist: ItemPropertyInfo
        TechResistBelowThreshold: ItemPropertyInfo
        TechShieldMaxHealth: ItemPropertyInfo
        TempTechShieldHealth: ItemPropertyInfo
        TetherDuration: ItemPropertyInfo
        TetherRadius: ItemPropertyInfo
        ThinkRate: ItemPropertyInfo
        TickRate: ItemPropertyInfo
        TossSpeed: ItemPropertyInfo
        TotalHealthRegen: ItemPropertyInfo
        TrackingSpeed: ItemPropertyInfo
        TurretAttackDelay: ItemPropertyInfo
        TurretAttackRange: ItemPropertyInfo
        TurretDeployTime: ItemPropertyInfo
        TurretLifetime: ItemPropertyInfo
        VerticalDifferenceTolerance: ItemPropertyInfo
        VexBarrierCombatBarrier: ItemPropertyInfo
        VisualContractRadius: ItemPropertyInfo
        WatcherMaxDuration: ItemPropertyInfo
        WeaponDamageBonusDuration: ItemPropertyInfo
        WeaponDamagePerStack: ItemPropertyInfo
        WeaponPower: ItemPropertyInfo
        WeaponPowerPerDeath: ItemPropertyInfo
        WeaponPowerPerKill: ItemPropertyInfo
        WeaponPowerPerStack: ItemPropertyInfo
        WeaponPowerWhileActivated: ItemPropertyInfo
    }

    type TooltipSection {
        section_type: String
        section_attributes: [ToolTipSectionAttributes]
    }

    type ToolTipSectionAttributes {
        loc_string: String
        properties: [String]
        important_properties: [String]
    }

    type Hero {
        id: ID!
        class_name: String!
        name: String!
        description: HeroDescription
        recommended_upgrades: [Item]
        recommended_ability_order: [String]
        player_selectable: Boolean
        disabled: Boolean
        in_development: Boolean
        needs_testing: Boolean
        assigned_players_only: Boolean
        limited_testing: Boolean
        complexity: Int
        skin: Int
        images: HeroImages
        items: HeroItems
        starting_stats: HeroStartingStats
    }

    type HeroDescription {
        lore: String
    }
    
    type HeroImages {
        icon_hero_card: String
        icon_hero_card_webp: String
        icon_image_small: String
        icon_image_small_webp: String
        minimap_image: String
        minimap_image_webp: String
        selection_image: String
        selection_image_webp: String
        top_bar_image: String
        top_bar_image_webp: String
    }

    type HeroItems {
        ability_climb_rope: Item
        ability_innate1: Item
        ability_innate2: Item
        ability_innate3: Item
        ability_jump: Item
        ability_mantle: Item
        ability_slide: Item
        ability_zip_line: Item
        ability_zip_line_boost: Item
        signature1: Item
        signature2: Item
        signature3: Item
        signature4: Item
        weapon_melee: Item
        weapon_primary: Item
        weapon_secondary: Item
    }

    type HeroStartingStats {
        max_move_speed: HeroStartingStatInfo
        sprint_speed: HeroStartingStatInfo
        crouch_speed: HeroStartingStatInfo
        move_acceleration: HeroStartingStatInfo
        light_melee_damage: HeroStartingStatInfo
        heavy_melee_damage: HeroStartingStatInfo
        max_health: HeroStartingStatInfo
        weapon_power: HeroStartingStatInfo
        reload_speed: HeroStartingStatInfo
        weapon_power_scale: HeroStartingStatInfo
        proc_build_up_rate_scale: HeroStartingStatInfo
        stamina: HeroStartingStatInfo
        base_health_regen: HeroStartingStatInfo
        stamina_regen_per_second: HeroStartingStatInfo
        ability_resource_max: HeroStartingStatInfo
        ability_resource_regen_per_second: HeroStartingStatInfo
        crit_damage_received_scale: HeroStartingStatInfo
        tech_duration: HeroStartingStatInfo
        tech_range: HeroStartingStatInfo
    }

    type HeroStartingStatInfo {
        value: Float
        display_stat_name: String
    }
`;

type Hero = {
	id: number;
	class_name: string;
	name: string;
	items: HeroItems;
};

/*
    values from REST API are Item class_names
    resolve to Item objects
*/
type HeroItems = {
	ability_climb_rope: string;
	ability_innate1: string;
	ability_innate2: string;
	ability_innate3: string;
	ability_jump: string;
	ability_mantle: string;
	ability_slide: string;
	ability_zip_line: string;
	ability_zip_line_boost: string;
	signature1: string;
	signature2: string;
	signature3: string;
	signature4: string;
	weapon_melee: string;
	weapon_primary: string;
	weapon_secondary: string;
};

type Item = {
	id: string;
	class_name: string;
	name: string;
	type: string;
	hero?: number;
	heroes?: number[];
};

export default typeDefs;
export type { Hero, Item };
